const $=s=>document.querySelector(s),view=$('#view'),modal=$('#modal'),modalContent=$('#modalContent');
const state={view:'home',q:'',family:'all',eunis:'all',hab:'EUNIS',gq:'',photos:JSON.parse(localStorage.botadex_photos||'{}')};
function save(){localStorage.botadex_photos=JSON.stringify(state.photos)}
function title(t,s){$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s}
function setView(v){state.view=v;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.download='botadex.json';a.href=URL.createObjectURL(new Blob([JSON.stringify(DATA,null,2)]));a.click()};
function render(){if(state.view==='home')home();if(state.view==='plants')plants();if(state.view==='habitats')habitats();if(state.view==='glossary')glossary()}
function home(){title('Accueil','Flore, habitats EUNIS et phytosociologie autour d’Angers.');view.innerHTML=`<div class="grid"><section class="card hero"><div><h2>Botadex</h2><p>Un outil naturaliste pour apprendre la flore autour d’Angers : reconnaître les plantes, comprendre leurs biotopes, relier les espèces aux habitats EUNIS et s’entraîner à la phytosociologie de terrain.</p><div class="actions"><button class="primary" onclick="setView('plants')">Explorer les plantes</button><button class="secondary" onclick="setView('habitats')">EUNIS / Phyto</button><button class="secondary" onclick="setView('glossary')">Glossaire</button></div></div><div class="hero-art">🌿</div></section><section class="card span-4"><h3>${DATA.plants.length}</h3><p>plantes réelles intégrées pour démarrer la base. Chaque fiche correspond à une plante nommée.</p></section><section class="card span-4"><h3>${DATA.habitats.length}</h3><p>habitats et classes EUNIS avec espèces indicatrices.</p></section><section class="card span-4"><h3>${DATA.syntaxons.length}</h3><p>syntaxons phytosociologiques utiles pour les relevés.</p></section><section class="card span-12 warn"><b>Objectif :</b> construire progressivement une base de 500 puis 1500 plantes observables autour d’Angers, avec une priorité aux espèces communes, indicatrices, protégées, patrimoniales et invasives. Les statuts réglementaires devront toujours être vérifiés avec les sources officielles.</section></div>`}
function plants(){title('Plantes','Classification, criteres, biotope, EUNIS, phyto et photos.');let f=['all',...new Set(DATA.plants.map(p=>p.family))].sort(),e=['all',...new Set(DATA.plants.map(p=>p.eunis))].sort();view.innerHTML=`<div class="toolbar"><input class="search" placeholder="Rechercher..." value="${state.q}" oninput="state.q=this.value;plantList()"><select class="select" onchange="state.family=this.value;plantList()">${f.map(x=>`<option value="${x}" ${x===state.family?'selected':''}>${x==='all'?'Toutes familles':x}</option>`).join('')}</select><select class="select" onchange="state.eunis=this.value;plantList()">${e.map(x=>`<option value="${x}" ${x===state.eunis?'selected':''}>${x==='all'?'Tous EUNIS':x}</option>`).join('')}</select></div><div id="plants"></div>`;plantList()}
function plantList(){let q=state.q.toLowerCase();let l=DATA.plants.filter(p=>(state.family==='all'||p.family===state.family)&&(state.eunis==='all'||p.eunis===state.eunis)&&Object.values(p).join(' ').toLowerCase().includes(q));$('#plants').innerHTML=`<p><b>${l.length}</b> plantes</p><div class="plant-grid">${l.map(card).join('')}</div>`}
function card(p){let ph=(state.photos[p.id]||[])[0];return `<article class="plant-card"><div class="plant-cover">${ph?`<img class="cover-img" src="${ph}">`:'🌿'}</div><div class="plant-body"><h3>${p.fr}</h3><div class="latin"><i>${p.latin}</i></div><div class="badges"><span class="badge">${p.family}</span><span class="badge">${p.eunis}</span><span class="badge">${p.syntaxon}</span></div><p>${p.criteria}</p><button onclick="openPlant(${p.id})">Fiche + photos</button></div></article>`}
function openPlant(id){let p=DATA.plants.find(x=>x.id===id),c=p.classif||{},ph=state.photos[id]||[];modalContent.innerHTML=`<h2>${p.fr}</h2><div class="latin"><i>${p.latin}</i> - ${p.family}</div><section class="module"><h3>Classification</h3><table><tr><td>Classe</td><td>${c.classe||'—'}</td></tr><tr><td>Ordre</td><td>${c.ordre||'—'}</td></tr><tr><td>Famille</td><td>${p.family}</td></tr></table></section><section class="module"><h3>Criteres d identification</h3><p>${p.criteria}</p><p><b>Confusions :</b> ${p.confusions}</p></section><section class="module"><h3>Biotope / habitat</h3><p><b>Biotope :</b> ${p.biotope}</p><p><b>EUNIS :</b> ${p.eunis}</p><p><b>Phytosociologie :</b> ${p.syntaxon}</p></section><h3>Photos</h3><div class="photo-grid">${[0,1,2,3,4,5].map(i=>`<label class="photo-slot">${ph[i]?`<img src="${ph[i]}">`:`Photo ${i+1}`}<input hidden type="file" accept="image/*" onchange="addPhoto(${id},${i},this)"></label>`).join('')}</div>`;modal.showModal()}
function addPhoto(id,i,input){let f=input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.photos[id]=state.photos[id]||[];state.photos[id][i]=r.result;save();openPlant(id);if(state.view==='plants')plantList()};r.readAsDataURL(f)}
function closeModal(){modal.close()}
function setHab(x){state.hab=x;habitats()}
function habitats(){title('EUNIS / Phytosociologie','Habitats, classes, syntaxons et especes indicatrices.');let h=`<div class="tabs"><button class="${state.hab==='EUNIS'?'active':''}" onclick="setHab('EUNIS')">EUNIS</button><button class="${state.hab==='Phyto'?'active':''}" onclick="setHab('Phyto')">Phytosociologie</button></div>`;if(state.hab==='EUNIS')h+=`<div class="module-list">${DATA.habitats.map(x=>`<article class="module"><h3>${x.code} - ${x.name}</h3><p><b>Classe :</b> ${x.classe}</p><p><b>Diagnostic :</b> ${x.diagnostic}</p><p><b>Indicatrices :</b> ${x.indicatrices}</p></article>`).join('')}</div>`;else h+=`<div class="module-list">${DATA.syntaxons.map(s=>`<article class="module"><h3>${s.name}</h3><p><b>Rang :</b> ${s.rang}</p><p><b>Milieu :</b> ${s.milieu}</p><p><b>Cortege :</b> ${s.especes}</p><p><b>EUNIS :</b> ${s.eunis}</p></article>`).join('')}</div>`;view.innerHTML=h}
function glossary(){title('Glossaire','Vocabulaire botanique complet.');let q=state.gq.toLowerCase();view.innerHTML=`<input class="search" placeholder="Rechercher..." value="${state.gq}" oninput="state.gq=this.value;glossary()"><div class="module-list">${DATA.glossary.filter(g=>(g.term+' '+g.simple).toLowerCase().includes(q)).map(g=>`<article class="definition"><div class="diagram">🌿</div><div><h3>${g.term}</h3><p>${g.simple}</p></div></article>`).join('')}</div>`}
render();
