// Botadex clean mode: une fiche = une plante reelle; focus plantes, EUNIS, phyto, glossaire.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
function bad(p){let s=(p.fr+' '+p.latin).toLowerCase();return s.includes('fiche locale')||/\b0{2,}\d+\b/.test(s)}
function key(p){return String(p.latin||p.fr||'').replace(' agg.','').trim().toLowerCase()}
let m=new Map();DATA.plants.filter(p=>!bad(p)).forEach(p=>{let k=key(p);if(k&&!m.has(k))m.set(k,p)});DATA.plants=[...m.values()].sort((a,b)=>String(a.fr).localeCompare(String(b.fr),'fr'));DATA.plants.forEach((p,i)=>p.id=i+1);
document.querySelector('[data-view="learn"]').textContent='📚 Glossaire';document.querySelector('[data-view="terrain"]').textContent='🌱 EUNIS / Phyto';
function v(x){return x||'—'}
window.home=function(){title('Accueil','Botadex propre : plantes reelles, habitats, EUNIS, phytosociologie et glossaire.');view.innerHTML=progressBlock()+`<div class="grid"><section class="card hero"><div><h2>Base propre, sans fiches locales numerotees.</h2><p>Une fiche correspond maintenant a une plante nommee. Les fiches artificielles du type 0031/0051 sont masquees. L objectif 1500 taxons sera atteint uniquement avec une vraie liste verifiee, pas avec des doublons.</p><div class="actions"><button class="primary" onclick="setView('explore')">Explorer les plantes</button><button class="secondary" onclick="setView('terrain')">EUNIS et phyto</button><button class="secondary" onclick="setView('learn')">Glossaire</button></div></div><div class="hero-art">🌿</div></section><section class="card span-4"><h3>${DATA.plants.length}</h3><p>plantes nommees actuellement visibles.</p></section><section class="card span-4"><h3>${DATA.habitats.length}</h3><p>habitats EUNIS / biotopes expliques.</p></section><section class="card span-4"><h3>${DATA.syntaxons.length}</h3><p>syntaxons phytosociologiques.</p></section><section class="card span-12 warn"><b>Important :</b> je ne remets pas de fausses fiches pour afficher 1500. Pour avoir 1500 taxons autour d Angers, il faut importer/valider une liste officielle CBN/INPN. L application est prete pour ca, mais elle ne doit plus inventer.</section></div>`};
window.explore=function(){title('Explorer','Plantes reelles avec classification, photos, criteres, biotope et habitats.');let fam=['all',...new Set(DATA.plants.map(p=>p.family))].sort(),hab=['all',...new Set(DATA.plants.map(p=>p.eunis||'—'))].sort();view.innerHTML=`<div class="toolbar"><input class="search" placeholder="Rechercher nom, latin, famille, habitat..." value="${state.q}" oninput="state.q=this.value;plantList()"><select class="select" onchange="state.family=this.value;plantList()">${fam.map(f=>`<option value="${f}" ${state.family===f?'selected':''}>${f==='all'?'Toutes familles':f}</option>`)}</select><select class="select" onchange="state.eunis=this.value;plantList()">${hab.map(h=>`<option value="${h}" ${state.eunis===h?'selected':''}>${h==='all'?'Tous EUNIS':h}</option>`)}</select></div><div id="plants"></div>`;plantList()};
window.plantList=function(){let q=(state.q||'').toLowerCase();let list=DATA.plants.filter(p=>(state.family==='all'||!state.family||p.family===state.family)&&((state.eunis||'all')==='all'||p.eunis===state.eunis)&&Object.values(p).join(' ').toLowerCase().includes(q));$('#plants').innerHTML=`<p><b>${list.length}</b> plantes</p><div class="plant-grid">${list.map(card).join('')}</div>`};
window.card=function(p){let ph=(state.photos[p.id]||[])[0];return `<article class="plant-card"><div class="plant-cover">${ph?`<img class="cover-img" src="${ph}">`:emo(p.group||'')}</div><div class="plant-body"><h3>${v(p.fr)}</h3><div class="latin"><i>${v(p.latin)}</i></div><div class="badges"><span class="badge">${v(p.family)}</span><span class="badge">${v(p.eunis)}</span><span class="badge">${v(p.syntaxon)}</span></div><p>${v(p.criteria)}</p><div class="mini-actions"><button onclick="openPlant(${p.id})">Fiche + photos</button><button onclick="mark(${p.id},'known')">Maîtrisé</button><button onclick="mark(${p.id},'learn')">À revoir</button></div></div></article>`};
window.openPlant=function(id){let p=DATA.plants.find(x=>x.id===id),photos=state.photos[id]||[],c=p.classif||{};modalContent.innerHTML=`<h2>${v(p.fr)}</h2><div class="latin"><i>${v(p.latin)}</i> · ${v(p.family)}</div><div class="badges"><span class="badge">${v(p.eunis)}</span><span class="badge">${v(p.syntaxon)}</span><span class="badge">${v(p.group)}</span></div><section class="module"><h3>Classification</h3><table><tr><td>Classe</td><td>${v(c.classe)}</td></tr><tr><td>Ordre</td><td>${v(c.ordre)}</td></tr><tr><td>Famille</td><td>${v(p.family)}</td></tr><tr><td>Taxon</td><td><i>${v(p.latin)}</i></td></tr></table></section><section class="module"><h3>Criteres d identification</h3><p>${v(p.criteria)}</p><p><b>Confusions :</b> ${v(p.confusions)}</p></section><section class="module"><h3>Biotope / habitat</h3><p><b>Biotope :</b> ${v(p.habitat)}</p><p><b>Ecologie :</b> ${v(p.ecology)}</p><p><b>EUNIS probable :</b> ${v(p.eunis)}. Une plante seule ne suffit jamais : il faut le cortege et la structure.</p><p><b>Phytosociologie :</b> ${v(p.syntaxon)}</p></section><h3>Photos personnelles</h3><div class="photo-grid">${[0,1,2,3,4,5].map(i=>`<label class="photo-slot">${photos[i]?`<img src="${photos[i]}">`:`Photo ${i+1}`}<input hidden type="file" accept="image/*" onchange="addPhoto(${id},${i},this)"></label>`).join('')}</div>`;modal.showModal()};
window.learn=function(){title('Glossaire','Glossaire botanique complet et utile pour la determination.');let q=state.gq||'';let terms=DATA.glossary||[];view.innerHTML=`<input class="search" placeholder="Rechercher un terme..." value="${q}" oninput="state.gq=this.value;learn()"><div class="module-list">${terms.filter(g=>(g.term+' '+g.simple+' '+g.expert).toLowerCase().includes(q.toLowerCase())).map(g=>gloss(g)).join('')}</div>`};
window.terrain=function(){title('EUNIS / Phytosociologie','Habitats, biotopes, syntaxons et corteges.');let t=tabs(['EUNIS','Phytosociologie'],state.terrain||'EUNIS','setTerrain');let h='';if((state.terrain||'EUNIS')==='EUNIS')h=`<div class="module-list">${DATA.habitats.map(x=>`<article class="module"><h3>${x.code} — ${x.name}</h3><p>${x.simple}</p><p><b>Terrain :</b> ${x.terrain}</p><p><b>Cortege :</b> ${x.cortège}</p><p><b>Confusions :</b> ${x.conf}</p></article>`).join('')}</div>`;else h=`<div class="module-list">${DATA.syntaxons.map(s=>`<article class="module"><h3>${s.name}</h3><p><b>Niveau :</b> ${s.level||'syntaxon'}</p><p><b>Ecologie :</b> ${s.ecology}</p><p><b>Cortege :</b> ${s.species}</p><p><b>EUNIS :</b> ${s.eunis||'a rattacher selon habitat'}</p><p><b>Phrase rapport :</b> ${s.report||''}</p></article>`).join('')}</div>`;view.innerHTML=t+h};
if(state.view==='home')home();else render();
})();