// Plantes communes prioritaires a ajouter aux fiches de base.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
const add=[
{fr:'Aigremoine eupatoire',latin:'Agrimonia eupatoria',family:'Rosaceae',group:'prairie',criteria:'Tige velue, feuilles composees pennées a folioles dentées, fleurs jaunes en long epi grele, fruits crochus qui s accrochent aux vetements.',habitat:'Prairies, ourlets, talus, lisières, chemins secs a mesophiles.',ecology:'Espece de milieux ouverts a semi-ouverts, souvent sur sols assez secs a frais.',confusions:'Autres Rosaceae jaunes ; regarder feuilles composees et fruits crochus.',eunis:'E2',syntaxon:'Arrhenatherion / ourlets prairiaux',expert:'Bonne espece pour apprendre feuilles composees, inflorescence en epi et fruits accrocheurs.'},
{fr:'Millepertuis perfore',latin:'Hypericum perforatum',family:'Hypericaceae',group:'prairie',criteria:'Feuilles opposees ponctuees de glandes translucides visibles a contre-jour, fleurs jaunes a 5 petales, nombreuses etamines, points noirs sur petales/sepales.',habitat:'Prairies seches, talus, friches, bords de chemins, ourlets clairs.',ecology:'Milieux ensoleilles, secs a mesophiles, souvent peu fertilises.',confusions:'Autres Hypericum ; verifier feuilles perforees, tige a deux lignes et ponctuations noires.',eunis:'E2',syntaxon:'Arrhenatheretalia / ourlets secs',expert:'Tres utile pour apprendre les feuilles opposees et les glandes translucides.'},
{fr:'Plantain lanceole',latin:'Plantago lanceolata',family:'Plantaginaceae',group:'prairie',criteria:'Rosette de feuilles lanceolees a nervures paralleles marquees, epi brun cylindrique, etamines saillantes a floraison.',habitat:'Prairies, pelouses, bords de chemins, zones pietinees moderement.',ecology:'Espece tres commune de milieux ouverts mesophiles.',confusions:'Plantago major et Plantago media ; comparer largeur des feuilles et longueur du petiole.',eunis:'E2',syntaxon:'Cynosurion / Arrhenatherion',expert:'Tres bonne espece pour comprendre rosette et nervation parallele.'},
{fr:'Lierre terrestre',latin:'Glechoma hederacea',family:'Lamiaceae',group:'ourlet',criteria:'Tige rampante, feuilles opposees reniformes crenelees, odeur aromatique, fleurs violet bleu bilabiees.',habitat:'Haies, ourlets, prairies fraiches, jardins, bords de chemins.',ecology:'Milieux frais, eutrophes a mesotrophes, semi-ombrages.',confusions:'Lamium, Veronica ; verifier tige rampante, odeur et feuilles reniformes.',eunis:'E5',syntaxon:'Glechometalia / ourlets nitrophiles',expert:'Parfait pour apprendre Lamiaceae, feuilles opposees et corolle bilabiee.'},
{fr:'Lotier corniculé',latin:'Lotus corniculatus',family:'Fabaceae',group:'prairie',criteria:'Feuilles a 5 folioles apparentes dont 2 basales, fleurs jaunes papilionacees en petites ombelles, gousses allongees.',habitat:'Prairies, pelouses, talus, bords de chemins.',ecology:'Milieux ouverts secs a mesophiles, assez pauvres a moyennement riches.',confusions:'Medicago, Trifolium ; verifier disposition des folioles et gousses.',eunis:'E2',syntaxon:'Cynosurion / Mesobromion selon contexte',expert:'Bonne espece pour apprendre Fabaceae et fleurs papilionacees.'},
{fr:'Potentille tormentille',latin:'Potentilla erecta',family:'Rosaceae',group:'prairie humide',criteria:'Petite Rosaceae a fleurs jaunes le plus souvent a 4 petales, feuilles palmees/trifoliees, milieux acides maigres.',habitat:'Landes, prairies humides maigres, bas-marais acides, lisières pauvres.',ecology:'Espece acidiphile, oligotrophe, hygrophile a mesophile.',confusions:'Autres Potentilla jaunes ; compter les petales et regarder le milieu.',eunis:'E3.4',syntaxon:'Molinion / Nardetalia',expert:'Tres utile comme indicatrice de milieux maigres acides.'}
];
let next=Math.max(...DATA.plants.map(p=>p.id||0))+1;
add.forEach(x=>{if(!DATA.plants.some(p=>p.latin===x.latin)){DATA.plants.unshift({...x,id:next++,detailed:true,classif:{regne:'Plantae',embranchement:'Tracheophytes',clade:'Angiospermes',classe:'Eudicotyledones',ordre:x.family==='Rosaceae'?'Rosales':x.family==='Fabaceae'?'Fabales':x.family==='Lamiaceae'?'Lamiales':x.family==='Plantaginaceae'?'Lamiales':'Malpighiales',famille:x.family,genre:x.latin.split(' ')[0],taxon:x.latin}})}});
if(typeof render==='function')render();
})();
