// Botadex reset propre. Une fiche = une plante nommee. Pas de doublons generes.
const DATA={target:1500};
const rows=`
Aigremoine eupatoire|Agrimonia eupatoria|Rosaceae|Rosales|Eudicotylédones|Prairies, talus, lisières, ourlets secs à mésophiles|E2/E5|Arrhenatherion / Trifolion medii|Tige velue, feuilles composées pennées, fleurs jaunes en long épi, fruits crochus.
Millepertuis perforé|Hypericum perforatum|Hypericaceae|Malpighiales|Eudicotylédones|Talus, friches, prairies sèches, bords de chemins|E2/E5|Arrhenatheretalia|Feuilles opposées ponctuées de glandes translucides, fleurs jaunes à nombreuses étamines, points noirs.
Grande ortie|Urtica dioica|Urticaceae|Rosales|Eudicotylédones|Ourlets nitrophiles, friches, berges enrichies|E5/J|Galio-Urticetea|Feuilles opposées dentées, poils urticants, inflorescences verdâtres pendantes.
Plantain lancéolé|Plantago lanceolata|Plantaginaceae|Lamiales|Eudicotylédones|Prairies, pelouses, chemins, zones piétinées|E2|Cynosurion / Arrhenatherion|Rosette, feuilles lancéolées à nervures parallèles, épi brun cylindrique.
Achillée millefeuille|Achillea millefolium|Asteraceae|Asterales|Eudicotylédones|Prairies, talus, bords de chemins|E2|Arrhenatherion|Feuilles très découpées, aspect plumeux, capitules blancs ou rosés en corymbe.
Centaurée jacée|Centaurea jacea|Asteraceae|Asterales|Eudicotylédones|Prairies de fauche, talus, ourlets|E2/E5|Arrhenatherion|Capitules pourpres, bractées scarieuses/frangées, feuilles alternes.
Pâquerette|Bellis perennis|Asteraceae|Asterales|Eudicotylédones|Pelouses, prairies rases, gazons|E2|Cynosurion|Petite rosette, capitules blancs à centre jaune, plante basse des pelouses.
Pissenlit|Taraxacum officinale agg.|Asteraceae|Asterales|Eudicotylédones|Prairies, gazons, friches, bords de routes|E2/J|Cynosurion|Rosette, feuilles dentées, capitules jaunes, akènes à aigrette, latex blanc.
Séneçon jacobée|Jacobaea vulgaris|Asteraceae|Asterales|Eudicotylédones|Friches, prairies, talus|E5/J|Artemisietea|Capitules jaunes, feuilles découpées, port dressé, floraison estivale.
Picride fausse-épervière|Picris hieracioides|Asteraceae|Asterales|Eudicotylédones|Friches, talus, prairies sèches|E5|Dauco-Melilotion|Capitules jaunes, feuilles rudes, tiges rameuses, latex.
Lotier corniculé|Lotus corniculatus|Fabaceae|Fabales|Eudicotylédones|Prairies, talus, pelouses, bords de chemins|E2|Cynosurion / Mesobromion|Fleurs jaunes papilionacées, feuilles à 5 folioles apparentes, gousses allongées.
Trèfle des prés|Trifolium pratense|Fabaceae|Fabales|Eudicotylédones|Prairies mésophiles, fauche, pâture|E2|Arrhenatherion / Cynosurion|Feuilles trifoliées souvent maculées, gros capitules roses pourpres.
Trèfle blanc|Trifolium repens|Fabaceae|Fabales|Eudicotylédones|Pelouses, prairies pâturées, chemins|E2|Cynosurion|Tiges rampantes, feuilles trifoliées, capitules blancs, enracinement aux nœuds.
Vesce commune|Vicia sativa|Fabaceae|Fabales|Eudicotylédones|Prairies, cultures, haies, friches|E2/I1|Secalietea / Arrhenatheretalia|Feuilles composées terminées par vrille, fleurs violettes, gousses.
Gesse des prés|Lathyrus pratensis|Fabaceae|Fabales|Eudicotylédones|Prairies fraîches, haies, lisières|E2/E3|Arrhenatherion|Fleurs jaunes, feuilles à une paire de folioles et vrille, stipules marquées.
Lierre terrestre|Glechoma hederacea|Lamiaceae|Lamiales|Eudicotylédones|Ourlets frais, haies, prairies fraîches, jardins|E5|Glechometalia|Tige rampante, feuilles opposées réniformes crénelées, odeur aromatique, fleurs violettes bilabiées.
Lamier pourpre|Lamium purpureum|Lamiaceae|Lamiales|Eudicotylédones|Cultures, jardins, friches, sols remaniés|J/I1|Stellarietea mediae|Tige carrée, feuilles opposées, haut de plante pourpré, fleurs bilabiées roses.
Menthe aquatique|Mentha aquatica|Lamiaceae|Lamiales|Eudicotylédones|Fossés, berges, prairies humides|E3/C3|Phragmito-Magnocaricetea|Odeur de menthe, feuilles opposées, inflorescences arrondies lilacées, milieux humides.
Brunelle commune|Prunella vulgaris|Lamiaceae|Lamiales|Eudicotylédones|Pelouses, prairies, chemins|E2|Cynosurion|Petite Lamiaceae à épi court, fleurs violettes, feuilles opposées.
Molinie bleue|Molinia caerulea|Poaceae|Poales|Monocotylédones|Prairies humides oligotrophes, landes humides|E3.4|Molinion caeruleae|Touffes denses, panicule fine souvent violacée, ligule réduite en rang de poils.
Houlque laineuse|Holcus lanatus|Poaceae|Poales|Monocotylédones|Prairies fraîches, talus, bords de chemins|E2/E3|Arrhenatherion|Graminée velue douce, panicule blanchâtre à rosée, feuilles pubescentes.
Dactyle aggloméré|Dactylis glomerata|Poaceae|Poales|Monocotylédones|Prairies, bords de chemins, lisières|E2/E5|Arrhenatherion|Panicule en glomérules denses, feuilles larges, gaine aplatie.
Flouve odorante|Anthoxanthum odoratum|Poaceae|Poales|Monocotylédones|Prairies maigres, pelouses|E2|Cynosurion / Nardetea|Petite graminée odorante au foin, épi lâche, floraison printanière.
Baldingère faux-roseau|Phalaris arundinacea|Poaceae|Poales|Monocotylédones|Berges, fossés, prairies inondables|E3/C3|Phalaridion|Grande graminée, feuilles larges, panicule d’abord compacte puis étalée.
Phragmite commun|Phragmites australis|Poaceae|Poales|Monocotylédones|Roselières, berges, marais, fossés|D5/C3|Phragmition|Très grand roseau, tiges robustes, panicule plumeuse, peuplements denses.
Carex panicea|Carex panicea|Cyperaceae|Poales|Monocotylédones|Prairies humides pauvres, bas-marais|E3.4/D2|Molinion / Caricion|Laîche glauque, épis mâles et femelles séparés, utricules à observer.
Carex pendula|Carex pendula|Cyperaceae|Poales|Monocotylédones|Boisements frais, suintements, fossés ombragés|G1/E3|Alnion / Caricion remotae|Grande laîche en touffes, épis pendants longs, milieux ombragés humides.
Carex remota|Carex remota|Cyperaceae|Poales|Monocotylédones|Ruisselets forestiers, suintements, bois humides|G1/C2|Caricion remotae|Laîche grêle, épis espacés, milieux forestiers humides.
Jonc acutiflore|Juncus acutiflorus|Juncaceae|Poales|Monocotylédones|Prairies humides acides, suintements|E3.4|Juncion acutiflori|Jonc à inflorescence lâche, tépales aigus, feuilles/tiges cloisonnées.
Jonc diffus|Juncus effusus|Juncaceae|Poales|Monocotylédones|Prairies humides, fossés, sols tassés|E3/D5|Calthion / Agrostietea|Grosse touffe, tiges cylindriques lisses, inflorescence latérale apparente.
Iris jaune|Iris pseudacorus|Iridaceae|Asparagales|Monocotylédones|Berges, fossés, mares, roselières|C3/D5|Phragmition|Grand hélophyte, feuilles en glaive, fleurs jaunes, rhizome.
Orchis bouffon|Anacamptis morio|Orchidaceae|Asparagales|Monocotylédones|Prairies maigres, pelouses, fauches peu intensives|E2|Cynosurion / Mesobromion|Orchidée, casque à nervures vertes, labelle trilobé ponctué, feuilles non tachetées.
Fritillaire pintade|Fritillaria meleagris|Liliaceae|Liliales|Monocotylédones|Prairies inondables, vallées alluviales|E3|Bromion racemosi / Cnidion|Fleur en cloche à damier pourpre, feuilles linéaires, prairie humide alluviale.
Succise des prés|Succisa pratensis|Caprifoliaceae|Dipsacales|Eudicotylédones|Prairies humides maigres, landes humides|E3.4|Molinion|Capitules bleu-violet, feuilles entières, cortège oligotrophe humide.
Scabieuse colombaire|Scabiosa columbaria|Caprifoliaceae|Dipsacales|Eudicotylédones|Pelouses sèches, prairies maigres, talus calcaires|E1/E2|Mesobromion|Capitules bleu lilas, feuilles découpées, pelouses sèches.
Knautie des champs|Knautia arvensis|Caprifoliaceae|Dipsacales|Eudicotylédones|Prairies, talus, ourlets|E2/E5|Arrhenatherion|Capitules lilas, feuilles opposées souvent découpées, plante robuste.
Potentille tormentille|Potentilla erecta|Rosaceae|Rosales|Eudicotylédones|Landes, prairies humides maigres, sols acides|E3.4/F4|Molinion / Nardetea|Petites fleurs jaunes souvent à 4 pétales, feuilles palmées, milieux pauvres acides.
Reine-des-prés|Filipendula ulmaria|Rosaceae|Rosales|Eudicotylédones|Mégaphorbiaies, prairies humides, fossés|E5/E3|Filipendulion|Grande vivace, feuilles composées, inflorescences crème parfumées.
Ronce commune|Rubus fruticosus agg.|Rosaceae|Rosales|Eudicotylédones|Haies, lisières, friches, fourrés|F3/E5|Prunetalia / Rubetalia|Tiges arquées épineuses, feuilles composées, fleurs blanches rosées, mûres.
Églantier|Rosa canina agg.|Rosaceae|Rosales|Eudicotylédones|Haies, fourrés, lisières, talus|F3/FA|Prunetalia|Arbuste épineux, feuilles composées, cynorrhodons rouges.
Aubépine monogyne|Crataegus monogyna|Rosaceae|Rosales|Eudicotylédones|Haies, fourrés, lisières|F3/FA|Prunetalia|Feuilles lobées, épines, fleurs blanches, un style, fruits rouges.
Prunellier|Prunus spinosa|Rosaceae|Rosales|Eudicotylédones|Haies, fourrés, lisières, friches|F3/FA|Prunetalia|Arbuste très épineux, fleurs blanches avant feuilles, prunelles noires.
Ficaire|Ficaria verna|Ranunculaceae|Ranunculales|Eudicotylédones|Bois frais, haies, prairies humides printanières|G1/E3|Fraxino-Quercion / Aegopodion|Feuilles cordées luisantes, fleurs jaunes brillantes, floraison précoce.
Renoncule âcre|Ranunculus acris|Ranunculaceae|Ranunculales|Eudicotylédones|Prairies fraîches à mésophiles|E2/E3|Cynosurion / Calthion|Fleurs jaunes brillantes, feuilles découpées, plante dressée.
Renoncule rampante|Ranunculus repens|Ranunculaceae|Ranunculales|Eudicotylédones|Prairies humides, sols tassés, fossés|E3/J|Agrostietea stoloniferae|Stolons rampants, fleurs jaunes, feuilles trilobées.
Compagnon rouge|Silene dioica|Caryophyllaceae|Caryophyllales|Eudicotylédones|Haies, lisières, bois frais, ourlets|E5/G1|Trifolion medii / Galio-Urticetea|Fleurs roses, feuilles opposées, plante velue, calice renflé.
Lychnis fleur-de-coucou|Silene flos-cuculi|Caryophyllaceae|Caryophyllales|Eudicotylédones|Prairies humides peu intensives|E3|Calthion / Bromion racemosi|Fleurs roses à pétales très découpés, feuilles opposées.
Mouron des oiseaux|Stellaria media|Caryophyllaceae|Caryophyllales|Eudicotylédones|Cultures, jardins, friches, sols nus|J/I1|Stellarietea mediae|Petites fleurs blanches, tige avec ligne de poils, feuilles opposées.
Gaillet gratteron|Galium aparine|Rubiaceae|Gentianales|Eudicotylédones|Haies, friches, ourlets nitrophiles|E5/J|Galio-Urticetea|Plante accrochante, feuilles verticillées, tiges rudes, fruits crochus.
Gaillet jaune|Galium verum|Rubiaceae|Gentianales|Eudicotylédones|Pelouses, prairies sèches, talus|E1/E2|Mesobromion|Feuilles verticillées fines, fleurs jaunes nombreuses, odeur miellée.
Liseron des haies|Calystegia sepium|Convolvulaceae|Solanales|Eudicotylédones|Haies, berges, friches fraîches|E5/J|Convolvuletalia|Grande liane herbacée, fleurs blanches en entonnoir, feuilles sagittées.
Morelle douce-amère|Solanum dulcamara|Solanaceae|Solanales|Eudicotylédones|Haies humides, roselières, berges|E5/C3|Convolvuletalia / Phragmitetea|Fleurs violettes à étamines jaunes, baies rouges, tige grimpante.
Gouet d’Italie|Arum italicum|Araceae|Alismatales|Monocotylédones|Haies, bois frais, talus ombragés|G1/E5|Fraxino-Quercion|Feuilles sagittées souvent veinées de blanc, spathe, épis de baies rouges.
Aulne glutineux|Alnus glutinosa|Betulaceae|Fagales|Eudicotylédones|Berges, ripisylves, bois marécageux|G1/C2|Alnion glutinosae|Feuilles arrondies tronquées, chatons, petits cônes ligneux noirs.
Frêne élevé|Fraxinus excelsior|Oleaceae|Lamiales|Eudicotylédones|Haies, bois frais, ripisylves|G1/FA|Fraxino-Quercion|Feuilles opposées composées, bourgeons noirs, samares.
Chêne pédonculé|Quercus robur|Fagaceae|Fagales|Eudicotylédones|Bois, haies, bocage, ripisylves hautes|G1/FA|Carpino-Fagetea|Feuilles lobées à court pétiole, glands pédonculés.
Charme|Carpinus betulus|Betulaceae|Fagales|Eudicotylédones|Bois, haies, taillis|G1/FA|Carpinion betuli|Feuilles doublement dentées gaufrées, fruits à bractées trilobées.
Noisetier|Corylus avellana|Betulaceae|Fagales|Eudicotylédones|Haies, lisières, sous-bois|F3/G1|Prunetalia / Carpino-Fagetea|Arbuste, feuilles rondes dentées, chatons mâles pendants, noisettes.
Saule blanc|Salix alba|Salicaceae|Malpighiales|Eudicotylédones|Berges, ripisylves, zones alluviales|G1/C3|Salicion albae|Arbre de berge, feuilles étroites argentées dessous, rameaux souples.
Saule cendré|Salix cinerea|Salicaceae|Malpighiales|Eudicotylédones|Fourrés humides, mares, fossés, bas-marais|F9/E3|Salicion cinereae|Arbuste, feuilles larges grisâtres dessous, chatons, bois strié sous écorce.
Bourdaine|Frangula alnus|Rhamnaceae|Rosales|Eudicotylédones|Bois humides, landes, tourbières boisées|F4/G1|Frangulo-Salicetea|Arbuste sans épines, feuilles entières nervées, baies rouges puis noires.
Callune|Calluna vulgaris|Ericaceae|Ericales|Eudicotylédones|Landes acides sèches à fraîches|F4|Calluno-Ulicetea|Sous-arbrisseau, feuilles en petites écailles opposées, fleurs roses.
Bruyère à quatre angles|Erica tetralix|Ericaceae|Ericales|Eudicotylédones|Landes humides acides, tourbières|F4/D1|Ericion tetralicis|Feuilles verticillées par 4, fleurs roses en grelots au sommet.
Fougère aigle|Pteridium aquilinum|Dennstaedtiaceae|Polypodiales|Polypodiopsida|Landes, lisières, coupes forestières, sols acides|E5/F4/G1|Pteridietalia|Grande fougère en nappes, fronde triangulaire très divisée, rhizome traçant.
Sphaignes|Sphagnum spp.|Sphagnaceae|Sphagnales|Sphagnopsida|Tourbières, suintements acides, landes humides|D1/D2|Scheuchzerio-Caricetea|Mousses spongieuses à capitulum, forte rétention d’eau, identification spécifique délicate.
Drosera à feuilles rondes|Drosera rotundifolia|Droseraceae|Caryophyllales|Eudicotylédones|Tourbières acides à sphaignes|D1|Oxycocco-Sphagnetea|Petite carnivore, feuilles rondes en rosette avec poils glanduleux rouges.
`.trim().split('\n');
DATA.plants=rows.map((r,i)=>{let a=r.split('|');return{id:i+1,fr:a[0],latin:a[1],family:a[2],classif:{ordre:a[3],classe:a[4],famille:a[2]},biotope:a[5],habitat:a[5],eunis:a[6],syntaxon:a[7],criteria:a[8],confusions:'À vérifier avec flore locale si doute.',ecology:a[5],photos:[]}});
DATA.habitats=[
{code:'E2',name:'Prairies mésophiles',classe:'Milieux herbacés',diagnostic:'Prairie ni très sèche ni très humide, graminées et dicotylédones prairiales.',indicatrices:'Achillea, Centaurea, Plantago, Trifolium, Dactylis.',degrade:'Surpâturage, fertilisation, banalisation.'},
{code:'E3',name:'Prairies humides',classe:'Milieux herbacés hygrophiles',diagnostic:'Sol frais à engorgé, joncs, carex, renoncules hygrophiles.',indicatrices:'Juncus, Carex, Silene flos-cuculi, Ranunculus repens.',degrade:'Drainage, eutrophisation, abandon.'},
{code:'E3.4',name:'Prairies humides oligotrophes',classe:'Milieux humides pauvres',diagnostic:'Prairie humide maigre à Molinie, Succise, Potentille tormentille.',indicatrices:'Molinia, Succisa, Carex panicea, Potentilla erecta.',degrade:'Fertilisation et drainage.'},
{code:'E5',name:'Ourlets et hautes herbes',classe:'Lisières et friches herbacées',diagnostic:'Végétation haute de lisière, friche ou bordure nitrophile.',indicatrices:'Urtica, Galium aparine, Glechoma, Calystegia.',degrade:'Rudéralisation excessive.'},
{code:'F3',name:'Fourrés tempérés',classe:'Ligneux bas',diagnostic:'Ronces, prunelliers, aubépines, jeunes ligneux.',indicatrices:'Rubus, Prunus spinosa, Crataegus, Rosa.',degrade:'Fermeture ou broyage trop fréquent.'},
{code:'F4',name:'Landes tempérées',classe:'Sous-arbrisseaux acidiphiles',diagnostic:'Callune, bruyères, ajoncs, fougère aigle sur sols acides.',indicatrices:'Calluna, Erica, Ulex, Pteridium.',degrade:'Enrésinement, fermeture, eutrophisation.'},
{code:'G1',name:'Boisements feuillus',classe:'Forêts',diagnostic:'Strate arborée feuillue, sous-bois, lisières.',indicatrices:'Quercus, Fraxinus, Carpinus, Corylus, Arum.',degrade:'Plantation, coupe, eutrophisation.'},
{code:'C2',name:'Eaux courantes',classe:'Aquatique',diagnostic:'Ruisseaux, rivières, berges, ripisylves.',indicatrices:'Alnus, Salix, Phalaris, Carex remota.',degrade:'Rectification, pollution.'},
{code:'C3/D5',name:'Berges, roselières et grands hélophytes',classe:'Zones humides',diagnostic:'Ceintures de roseaux, iris, typha, grandes herbes de bord d’eau.',indicatrices:'Phragmites, Iris pseudacorus, Phalaris.',degrade:'Eutrophisation, curage.'},
{code:'D1/D2',name:'Tourbières et bas-marais',classe:'Tourbeux',diagnostic:'Sphaignes, eau acide, espèces oligotrophes.',indicatrices:'Sphagnum, Drosera, Erica tetralix, Carex panicea.',degrade:'Drainage, piétinement, enrichissement.'}
];
DATA.syntaxons=[
{name:'Arrhenatherion',rang:'alliance',milieu:'Prairies mésophiles de fauche',especes:'Arrhenatherum, Dactylis, Centaurea, Achillea, Trifolium pratense',eunis:'E2'},
{name:'Cynosurion',rang:'alliance',milieu:'Prairies pâturées et pelouses mésophiles',especes:'Plantago lanceolata, Trifolium repens, Bellis, Lolium',eunis:'E2'},
{name:'Molinion caeruleae',rang:'alliance',milieu:'Prairies humides oligotrophes',especes:'Molinia, Succisa, Carex panicea, Potentilla erecta',eunis:'E3.4'},
{name:'Calthion',rang:'alliance',milieu:'Prairies humides eutrophes à mésotrophes',especes:'Juncus, Ranunculus repens, Silene flos-cuculi',eunis:'E3'},
{name:'Filipendulion',rang:'alliance',milieu:'Mégaphorbiaies humides',especes:'Filipendula ulmaria, Angelica, Lythrum',eunis:'E5/E3'},
{name:'Phragmition',rang:'alliance',milieu:'Roselières et grands hélophytes',especes:'Phragmites, Iris pseudacorus, Typha',eunis:'D5/C3'},
{name:'Prunetalia',rang:'ordre',milieu:'Haies et fourrés',especes:'Prunus spinosa, Crataegus, Rosa, Rubus',eunis:'F3/FA'},
{name:'Calluno-Ulicetea',rang:'classe',milieu:'Landes acides',especes:'Calluna, Erica, Ulex, Pteridium',eunis:'F4'},
{name:'Galio-Urticetea',rang:'classe',milieu:'Ourlets nitrophiles',especes:'Urtica, Galium aparine, Glechoma, Calystegia',eunis:'E5/J'}
];
DATA.glossary=[
['Limbe','Partie plate de la feuille.'],['Pétiole','Petit axe reliant le limbe à la tige.'],['Sessile','Sans pétiole.'],['Stipule','Petit appendice à la base du pétiole.'],['Gaine','Base de feuille entourant la tige, fréquente chez Poaceae.'],['Ligule','Petite membrane ou ligne de poils entre gaine et limbe chez les Poaceae.'],['Nervation pennée','Nervures secondaires partant d’une nervure centrale.'],['Nervation parallèle','Nervures parallèles, fréquentes chez monocotylédones.'],['Lancéolé','En forme de lance, allongé et rétréci aux extrémités.'],['Oblong','Allongé à bords presque parallèles.'],['Elliptique','En forme d’ellipse.'],['Cordé','En forme de cœur à la base.'],['Réniforme','En forme de rein.'],['Denté','Marge à dents pointues.'],['Crénelé','Marge à dents arrondies.'],['Lobé','Marge découpée en lobes.'],['Glabre','Sans poils.'],['Pubescent','Couvert de poils fins.'],['Hirsute','À poils longs et raides.'],['Capitule','Inflorescence dense typique des Asteraceae.'],['Ombelle','Inflorescence dont les pédoncules partent d’un même point.'],['Épi','Fleurs sessiles disposées le long d’un axe.'],['Panicule','Inflorescence ramifiée.'],['Akène','Fruit sec indéhiscent à une graine.'],['Capsule','Fruit sec qui s’ouvre à maturité.'],['Gousse','Fruit des Fabaceae.'],['Utricule','Organe enveloppant le fruit chez Carex.'],['Hélophyte','Plante enracinée sous l’eau ou dans la vase, avec tiges émergées.'],['Hygrophile','Qui aime les milieux humides.'],['Mésophile','Qui préfère les conditions moyennes en eau.'],['Xérophile','Qui supporte ou préfère les milieux secs.'],['Oligotrophe','Pauvre en nutriments.'],['Mésotrophe','Moyennement riche en nutriments.'],['Eutrophe','Riche en nutriments.'],['Dystrophe','Milieu déséquilibré, souvent riche en matière organique mal décomposée.'],['Cortège','Ensemble des espèces présentes ensemble dans un habitat.'],['Espèce caractéristique','Espèce fortement liée à une communauté végétale.'],['Espèce différentielle','Espèce qui aide à distinguer deux communautés proches.'],['Compagne','Espèce présente mais peu diagnostique.'],['Alliance','Rang phytosociologique regroupant des associations proches.'],['Association','Unité phytosociologique de terrain fondée sur un cortège.'],['EUNIS','Typologie européenne des habitats.'],['Biotope','Milieu physique de vie : sol, eau, lumière, gestion, trophie.']].map((x,i)=>({id:i+1,term:x[0],simple:x[1],expert:x[1]}));
