// Module expert Angers 100 km : habitats, phyto, Natura 2000, pédagogie.
(function(){
  const EH=[
    ['C2','Eaux courantes, ruisseaux et fossés courants','Milieux avec écoulement perceptible.','Observer courant, substrat, berges, ripisylve, herbiers.','Glyceria, Apium, Veronica beccabunga, Ranunculus aquatiques.','C1 si eau stagnante ; D5 si hélophytes dominants.','Recalibrage, curage, pollution, rupture ripisylve.','Rivières à herbiers aquatiques possibles.','Fort si cours naturel et continu.'],
    ['C3','Végétations amphibies, vases exondées et grèves','Petites végétations pionnières des berges et mares temporaires.','Chercher petites annuelles, substrat nu, alternance immersion/exondation.','Juncus bufonius, Lythrum portula, Isolepis, Cyperus, Bidens.','Prairie piétinée humide ou friche rudérale.','Stabilisation des niveaux, eutrophisation, piétinement.','Végétations de grèves et mares temporaires.','Fort si cortège pionnier rare.'],
    ['D1-D2','Tourbières, bas-marais et sphaignes','Milieux engorgés avec tourbe ou fonctionnement tourbeux.','Sphaignes, Drosera, tourbe, eau acide, suintements.','Sphagnum, Drosera, Erica tetralix, Carex panicea, Molinia.','Prairie humide sans tourbe ; lande humide sans sphaignes.','Drainage, boisement, plantation, eutrophisation.','Tourbières acides, bas-marais.','Très fort si typique.'],
    ['E1','Pelouses sèches, acidiphiles et sablo-calcaires','Végétation basse sur sol pauvre, sec ou drainant.','Sol superficiel, faible hauteur, xérophiles, orchidées.','Festuca ovina, Thymus, Sedum, orchidées.','E2 prairie maigre ; F4 lande.','Fermeture, fertilisation, abandon.','Pelouses sèches semi-naturelles.','Fort si riche et ancienne.'],
    ['E5','Ourlets, friches, mégaphorbiaies et hautes herbes','Végétation haute, de lisière, humide ou rudérale.','Hauteur, nitrophilie, humidité, abandon, invasives.','Urtica, Galium, Filipendula, Eupatorium, Cirsium, Rubus.','E2/E3 si prairie ; F3 si ligneux dominants.','Rudéralisation, fermeture, invasives.','Mégaphorbiaies hygrophiles possibles.','Faible à fort selon naturalité.'],
    ['F3','Fourrés, ronciers, saulaies arbustives','Milieux dominés par arbustes, ronces ou saules.','Dominance ligneuse basse, dynamique de fermeture.','Rubus, Prunus spinosa, Crataegus, Rosa, Salix cinerea, Ulex.','FA haie si linéaire ; G1 si arbres dominants.','Fermeture, broyage, invasives.','Important en mosaïque.','Modéré, fort en zone humide.'],
    ['FA','Haies bocagères, talus, arbres têtards et corridors','Linéaires boisés du bocage.','Strates, continuité, largeur, talus, vieux arbres, cavités.','Quercus, Fraxinus, Crataegus, Prunus spinosa, Corylus, Hedera.','F3 fourré ; G1 boisement large.','Arasement, coupe sévère, discontinuité.','Trame verte majeure.','Modéré à fort.'],
    ['G3','Plantations, résineux, peupleraies et boisements artificiels','Boisements plantés ou fortement artificialisés.','Alignements, homogénéité, sous-bois pauvre, drainage.','Peuplier, pin, robinier, strate banalisée.','G1 si boisement naturel.','Artificialisation, drainage.','Enjeu possible si zone humide résiduelle.','Faible à modéré.'],
    ['H3','Falaises, affleurements, vieux murs et rochers','Milieux minéraux à fougères, mousses, saxicoles.','Substrat, ombrage, suintement, fissures, vieux murs.','Asplenium, Polypodium, Sedum, bryophytes.','Talus sec ou friche.','Ravalement, fermeture.','Rochers siliceux/calcaires selon contexte.','Modéré à fort.'],
    ['I1','Cultures, messicoles, jachères et bordures agricoles','Milieux agricoles travaillés, parfois riches en messicoles.','Travail du sol, intrants, bordures, annuelles printanières.','Papaver, Centaurea cyanus, Legousia, Anthemis, Veronica.','J friche ; E2 prairie temporaire.','Herbicides, intensification.','Enjeu possible pour messicoles.','Souvent faible, fort si messicoles rares.'],
    ['J','Zones bâties, jardins, routes, remblais','Milieux très anthropisés.','Sol remanié, rudérales, invasives, vieux murs, noues.','Erigeron, Buddleja, Robinia, Senecio, Plantago, Poa annua.','E5 friche semi-naturelle.','Artificialisation, pollution, invasives.','Vigilance espèces protégées/invasives.','Faible à modéré.'],
    ['X','Complexes d’habitats et mosaïques bocagères/alluviales','Mosaïques : prairie, mare, haie, fossé, fourré.','Cartographier chaque unité ou noter proportions/fonctions.','E2, E3, FA, C1, D5, F3, G1.','Généraliser trop vite en un seul habitat.','Fragmentation, drainage, intensification.','Très important en vallées alluviales.','Souvent fort par fonctionnalité.']
  ];
  DATA.habitats=[...DATA.habitats,...EH.map(x=>({code:x[0],name:x[1],simple:x[2],terrain:x[3],cortège:x[4],conf:x[5],degradation:x[6],natura:x[7],enjeu:x[8],report:'Habitat '+x[0]+' à diagnostiquer par structure, cortège, sol, hydrologie et gestion.'}))].filter((h,i,a)=>a.findIndex(y=>y.code===h.code&&y.name===h.name)===i);
  const ES=[
    ['Arrhenatherion elatioris','Prairies de fauche mésophiles','Arrhenatherum, Centaurea, Leucanthemum, Trifolium.','E2'],
    ['Cynosurion cristati','Prairies pâturées mésophiles','Cynosurus, Trifolium repens, Bellis, Lolium.','E2'],
    ['Calthion palustris','Prairies humides fauchées','Caltha, Cardamine pratensis, Lychnis flos-cuculi.','E3'],
    ['Filipendulion ulmariae','Mégaphorbiaies humides','Filipendula, Eupatorium, Angelica, Lythrum.','E5/D5'],
    ['Bidention / Chenopodion rubri','Grèves vaseuses exondées','Bidens, Chenopodium rubrum, Persicaria, Cyperus.','C3'],
    ['Salicion albae','Saulaies riveraines','Salix alba, Populus nigra, Phalaris, Urtica.','G1'],
    ['Stellarietea mediae','Cultures et annuelles rudérales','Stellaria, Capsella, Veronica persica, Lamium.','I1/J']
  ];
  DATA.syntaxons=[...DATA.syntaxons,...ES.map(x=>({name:x[0],level:'Syntaxon majeur',group:x[1],ecology:'Syntaxon à connaître dans un rayon de 100 km autour d’Angers.',cortège:x[2],diff:'À confirmer par relevé homogène et cortège complet.',conf:'Attention aux formes dégradées ou artificialisées.',eunis:x[3],enjeu:'Variable selon typicité et état de conservation.',report:'Le cortège observé peut orienter vers '+x[0]+' sous réserve de validation phytosociologique.'}))].filter((s,i,a)=>a.findIndex(y=>y.name===s.name)===i);
  DATA.learning.push(
    {step:'Plan accéléré 30 jours',goal:'Progresser vite comme chargée d’étude flore.',lesson:'Alterner morphologie, familles, habitats, fiches plantes, relevés et rédaction BE.',exercise:'Chaque sortie : 1 relevé, 5 photos, 3 inconnues à clé, 1 phrase de diagnostic.',correction:'Le progrès vient de la répétition terrain + correction des erreurs.'},
    {step:'Méthode BE complète',goal:'Ne rien oublier dans un diagnostic flore-habitats.',lesson:'Zonages, bibliographie, période, protocole, cartographie, relevés, espèces protégées/invasives, EUNIS, phyto, enjeux, ERC.',exercise:'Fais une check-list avant chaque sortie.',correction:'Un bon rapport explique aussi les limites et incertitudes.'},
    {step:'Natura 2000 autour d’Angers',goal:'Identifier les habitats et fonctions sensibles.',lesson:'Priorités : Basses Vallées Angevines, Loire, bocage, prairies inondables, mares, haies, grèves, ripisylves et milieux alluviaux.',exercise:'Pour chaque site, lister habitats, espèces, fonctions hydrologiques et pressions.',correction:'Toujours vérifier DOCOB, FSD, INPN et DREAL avant conclusion.'}
  );
  DATA.expertAngers={radius:'100 km autour d’Angers',mustNotForget:['Basses Vallées Angevines : prairies inondables, bocage, mares, haies, flore humide potentielle','Vallée de la Loire : grèves, îles, boisements alluviaux, pelouses sèches, végétations amphibies','Bocage : corridors, vieux arbres, mares prairiales','Milieux acides : landes, tourbières, prairies à Molinie','Coteaux secs : pelouses, orchidées, ourlets','Zones agricoles : messicoles, bordures, invasives','Milieux urbains : vieux murs, friches, noues, invasives'],beChecklist:['Zonages : Natura 2000, ZNIEFF, APPB, ENS, zones humides, TVB','Bibliographie : INPN/TAXREF, CBN, DREAL, HabRef/EUNIS, listes rouges','Terrain : saison adaptée, météo, accès, homogénéité','Données : GPS, photos, coefficients, surface, sol, hydrologie','Analyse : EUNIS + syntaxon + état + fonctionnalité','Enjeux : espèces protégées, habitats patrimoniaux, invasives, continuités','Rapport : cartes, méthodes, limites, impacts, mesures ERC']};
})();
