// Botadex clean: une fiche = une plante reelle; focus plantes, EUNIS, phyto, glossaire.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
function bad(p){let s=(p.fr+' '+p.latin).toLowerCase();return s.includes('fiche locale')||/\b0{2,}\d+\b/.test(s)}
function key(p){return String(p.latin||p.fr||'').replace(' agg.','').trim().toLowerCase()}
let m=new Map();DATA.plants.filter(p=>!bad(p)).forEach(p=>{let k=key(p);if(k&&!m.has(k))m.set(k,p)});DATA.plants=[...m.values()].sort((a,b)=>String(a.fr).localeCompare(String(b.fr),'fr'));DATA.plants.forEach((p,i)=>p.id=i+1);
let bl=document.querySelector('[data-view="learn"]');if(bl)bl.textContent='📚 Glossaire';let bt=document.querySelector('[data-view="terrain"]');if(bt)bt.textContent='🌱 EUNIS / Phyto';
function vv(x){return x||'—'}
window.home=function(){title('Accueil','Botadex propre : plantes reelles, EUNIS, phytosociologie, glossaire.');view.innerHTML=progressBlock()+`<div class="grid"><section class="card hero"><div><h2>Base propre, sans fiches locales numerotees.</h2><p>Une fiche = une plante nommee. Les anciennes fiches artificielles 0031/0051 sont masquees. Objectif final : 1500 taxons verifies autour d Angers, mais uniquement avec une vraie liste fiable.</p><div class="actions"><button class="primary" onclick="setView('explore')">Explorer les plantes</button><button class="secondary" onclick="setView('terrain')">EUNIS et phyto</button><button class="secondary" onclick="setView('learn')">Glossaire</button></div></div><div class="hero-art">🌿</div></section><section class="card span-4"><h3>${DATA.plants.length}</h3><p>plantes nommees visibles.</p></section><section class="card span-4"><h3>${DATA.habitats.length}</h3><p>habitats EUNIS.</p></section><section class="card span-4"><h3>${DATA.syntaxons.length}</h3><p>syntaxons phyto.</p></section><section class="card span-12 warn">Je ne remets pas de fausses fiches pour afficher 1500. Pour atteindre 1500 proprement, il faut importer une liste CBN/INPN ou enrichir par lots de vraies especes.</section></div>`};
window.explore=function(){title('Explorer','Plantes reelles avec classification, criteres, biotope et photos.');let fam=['all',...new Set(DATA.plants.map(p=>p.family))].sort();let eu=['all',...new Set(DATA.plants.map(p=>p.eunis||'—'))].sort();view.innerHTML=`<div class="toolbar"><input class="search" placeholder="Rechercher nom, latin, famille, habitat..." value="${state.q}" oninput="state.q=this.value;plantList()"><select class="select" onchange="state.family=this.value;plantList()">${fam.map(f=>`<option value="${f}" ${state.family===f?'selected':''}>${f==='all'?'Toutes familles':f}</option>`)}</select><select class="select" onchange="state.eunis=this.value;plantList()">${eu.map(e=>`<option value="${e}" ${(state.eunis||'all')===e?'selected':''}>${e==='all'?'Tous EUNIS':e}</option>`)}</select></div><div id="plants"></div>`;plantList()};
window.plantList=function(){let q=(state.q||'').toLowerCase();let l=DATA.plants.filter(p=>(!state.family||state.family==='all'||p.family===state.family)&&((state.eunis||'all')==='all'||p.eunis===state.eunis)&&Object.values(p).join(' ').toLowerCase().includes(q));$('#plants').innerHTML=`<p><b>${l.length}</b> plantes</p><div class="plant-grid">${l.map(card).join('')}</div>`};
window.card=function(p){let ph=(state.photos[p.id]||[])[0];return `<article class="plant-card"><div class="plant-cover">${ph?`<img class="cover-img" src="${ph}">`:emo(p.group||'')}</div><div class="plant-body"><h3>${vv(p.fr)}</h3><div class="latin"><i>${vv(p.latin)}</i></div><div class="badges"><span class="badge">${vv(p.family)}</span><span class="badge">${vv(p.eunis)}</span><span class="badge">${vv(p.syntaxon)}</span></div><p>${vv(p.criteria)}</p><div class="mini-actions"><button onclick="openPlant(${p.id})">Fiche + photos</button><button onclick="mark(${p.id},'known')">Maîtrisé</button><button onclick="mark(${p.id},'learn')">À revoir</button></div></div></article>`};
window.openPlant=function(id){let p=DATA.plants.find(x=>x.id===id),photos=state.photos[id]||[],c=p.classif||{};modalContent.innerHTML=`<h2>${vv(p.fr)}</h2><div class="latin"><i>${vv(p.latin)}</i> · ${vv(p.family)}</div><div class="badges"><span class="badge">${vv(p.eunis)}</span><span class="badge">${vv(p.syntaxon)}</span><span class="badge">${vv(p.group)}</span></div><section class="module"><h3>Classification</h3><table><tr><td>Classe</td><td>${vv(c.classe)}</td></tr><tr><td>Ordre</td><td>${vv(c.ordre)}</td></tr><tr><td>Famille</td><td>${vv(p.family)}</td></tr><tr><td>Taxon</td><td><i>${vv(p.latin)}</i></td></tr></table></section><section class="module"><h3>Criteres d identification</h3><p>${vv(p.criteria)}</p><p><b>Confusions :</b> ${vv(p.confusions)}</p></section><section class="module"><h3>Biotope / habitat</h3><p><b>Biotope :</b> ${vv(p.habitat)}</p><p><b>Ecologie :</b> ${vv(p.ecology)}</p><p><b>EUNIS probable :</b> ${vv(p.eunis)}</p><p><b>Phytosociologie :</b> ${vv(p.syntaxon)}</p></section><h3>Photos personnelles</h3><div class="photo-grid">${[0,1,2,3,4,5].map(i=>`<label class="photo-slot">${photos[i]?`<img src="${photos[i]}">`:`Photo ${i+1}`}<input hidden type="file" accept="image/*" onchange="addPhoto(${id},${i},this)"></label>`).join('')}</div>`;modal.showModal()};
window.learn=function(){title('Glossaire','Glossaire botanique.');let q=state.gq||'';let gl=DATA.glossary||[];view.innerHTML=`<input class="search" placeholder="Rechercher un terme..." value="${q}" oninput="state.gq=this.value;learn()"><div class="module-list">${gl.filter(g=>(g.term+' '+g.simple+' '+g.expert).toLowerCase().includes(q.toLowerCase())).map(g=>gloss(g)).join('')}</div>`};
window.terrain=function(){title('EUNIS / Phytosociologie','Habitats et syntaxons utiles.');let active=state.terrain||'EUNIS';let h=tabs(['EUNIS','Phytosociologie'],active,'setTerrain');if(active==='EUNIS')h+=`<div class="module-list">${DATA.habitats.map(x=>`<article class="module"><h3>${x.code} — ${x.name}</h3><p>${x.simple}</p><p><b>Terrain :</b> ${x.terrain}</p><p><b>Cortege :</b> ${x.cortège}</p></article>`).join('')}</div>`;else h+=`<div class="module-list">${DATA.syntaxons.map(s=>`<article class="module"><h3>${s.name}</h3><p><b>Ecologie :</b> ${s.ecology}</p><p><b>Cortege :</b> ${s.species}</p><p><b>EUNIS :</b> ${s.eunis||'a rattacher selon habitat'}</p></article>`).join('')}</div>`;view.innerHTML=h};
if(state.view==='home')home();else render();
})();