// Botadex : taxonomie et critères d’identification vérifiés/propres, sans undefined.
(function(){
  const F={Asteraceae:['Eudicotylédones','Asterales','Capitules composés de fleurs ligulées/tubulées, involucre de bractées, fruits en akènes/cypsèles.'],Poaceae:['Monocotylédones','Poales','Tige à nœuds, feuilles à gaine, ligule, épillets avec glumes/lemmes.'],Cyperaceae:['Monocotylédones','Poales','Tige souvent triangulaire, feuilles en trois rangs, épis, utricules chez Carex.'],Juncaceae:['Monocotylédones','Poales','Tiges ou feuilles joncoïdes, fleurs discrètes à 6 tépales, capsules, milieux souvent humides.'],Ericaceae:['Eudicotylédones','Ericales','Sous-arbrisseaux acidiphiles, feuilles petites/coriaces, fleurs en grelots ou corolles.'],Fabaceae:['Eudicotylédones','Fabales','Feuilles souvent composées, stipules fréquentes, fleurs papilionacées, fruits en gousses.'],Rosaceae:['Eudicotylédones','Rosales','Fleurs souvent à 5 pétales et nombreuses étamines, stipules fréquentes, fruits variés.'],Caryophyllaceae:['Eudicotylédones','Caryophyllales','Feuilles opposées, nœuds marqués, fleurs souvent à 5 pétales, capsule fréquente.'],Orchidaceae:['Monocotylédones','Asparagales','Fleur zygomorphe avec labelle, ovaire infère, feuilles entières souvent basales.'],Iridaceae:['Monocotylédones','Asparagales','Feuilles en glaive, fleurs à 6 tépales, ovaire infère, souvent rhizome.'],Betulaceae:['Eudicotylédones','Fagales','Ligneux à feuilles simples, fleurs en chatons, fruits petits, critères sur feuilles et infrutescences.'],Urticaceae:['Eudicotylédones','Rosales','Feuilles souvent opposées, poils urticants possibles, petites fleurs verdâtres.'],Caprifoliaceae:['Eudicotylédones','Dipsacales','Feuilles souvent opposées, inflorescences compactes, fruits variables.'],Sphagnaceae:['Sphagnopsida','Sphagnales','Mousse spongieuse à capitulum terminal et rameaux fasciculés, milieux tourbeux.'],Dennstaedtiaceae:['Polypodiopsida','Polypodiales','Fougères à frondes divisées, sores et rhizome à observer.'],Droseraceae:['Eudicotylédones','Caryophyllales','Petites plantes carnivores à poils glanduleux, milieux tourbeux acides.']};
  const V={
    'Achillea millefolium':['Achillée millefeuille','Asteraceae','Achillea','Feuilles alternes très découpées bi- à tripennatiséquées, aspect plumeux, odeur aromatique, capitules blancs à rosés en corymbe plat, fruits en cypsèles.'],
    'Centaurea jacea':['Centaurée jacée','Asteraceae','Centaurea','Capitules pourpres, bractées de l’involucre scarieuses/frangées, feuilles alternes, prairie de fauche ou ourlet mésophile.'],
    'Molinia caerulea':['Molinie bleue','Poaceae','Molinia','Graminée en touffes denses, feuilles longues étroites, ligule réduite en rang de poils, panicule fine souvent violacée, sols humides acides.'],
    'Succisa pratensis':['Succise des prés','Caprifoliaceae','Succisa','Feuilles entières, capitules bleu-violet hémisphériques, prairie humide maigre, souvent avec Molinia, Carex panicea et Potentilla erecta.'],
    'Carex panicea':['Carex panicea','Cyperaceae','Carex','Laîche glauque de prairie humide, épis mâles/femelles séparés, utricules mûrs à observer, indicatrice de milieux pauvres.'],
    'Juncus acutiflorus':['Jonc acutiflore','Juncaceae','Juncus','Jonc de prairie humide acide, inflorescence lâche, tépales aigus, feuilles/tiges cloisonnées à vérifier.'],
    'Iris pseudacorus':['Iris jaune','Iridaceae','Iris','Grand hélophyte à feuilles en glaive, nervure médiane marquée, fleurs jaune vif, rhizome, capsule allongée, bords d’eau.'],
    'Phragmites australis':['Phragmite commun','Poaceae','Phragmites','Très grand roseau, tiges robustes, feuilles larges, panicule terminale plumeuse, peuplements denses en roselière.'],
    'Calluna vulgaris':['Callune','Ericaceae','Calluna','Sous-arbrisseau bas, petites feuilles opposées imbriquées, fleurs rosées, tiges ligneuses, landes acides.'],
    'Erica tetralix':['Bruyère à quatre angles','Ericaceae','Erica','Bruyère de lande humide, feuilles verticillées par 4, fleurs roses en grelots en tête terminale, souvent avec Molinia et sphaignes.'],
    'Urtica dioica':['Grande ortie','Urticaceae','Urtica','Vivace nitrophile, feuilles opposées dentées, poils urticants, inflorescences verdâtres pendantes, sols riches en azote.'],
    'Robinia pseudoacacia':['Robinier faux-acacia','Fabaceae','Robinia','Arbre à feuilles composées imparipennées, stipules épineuses, grappes de fleurs blanches, gousses, espèce exotique colonisatrice.'],
    'Anacamptis morio':['Orchis bouffon','Orchidaceae','Anacamptis','Orchidée prairiale, feuilles non tachetées en rosette, inflorescence lâche, sépales à nervures vertes, labelle trilobé ponctué.'],
    'Alnus glutinosa':['Aulne glutineux','Betulaceae','Alnus','Arbre de zones humides, feuilles arrondies souvent tronquées au sommet, jeunes feuilles glutineuses, chatons et petits cônes ligneux noirs.'],
    'Filipendula ulmaria':['Reine-des-prés','Rosaceae','Filipendula','Grande vivace hygrophile, feuilles composées à grande foliole terminale, inflorescences crème mousseuses et parfumées.'],
    'Silene flos-cuculi':['Lychnis fleur-de-coucou','Caryophyllaceae','Silene','Prairie humide, fleurs roses à pétales très découpés en lanières, feuilles opposées, tige fine.'],
    'Phalaris arundinacea':['Baldingère faux-roseau','Poaceae','Phalaris','Grande graminée de berges, feuilles larges, panicule d’abord compacte puis étalée, fossés et prairies inondables.'],
    'Sphagnum spp.':['Sphaignes','Sphagnaceae','Sphagnum','Mousse spongieuse des tourbières, capitulum terminal, rameaux en faisceaux, forte rétention d’eau, identification spécifique délicate.'],
    'Pteridium aquilinum':['Fougère aigle','Dennstaedtiaceae','Pteridium','Grande fougère en nappes, fronde triangulaire très divisée, long rhizome traçant, landes et coupes acides.'],
    'Drosera rotundifolia':['Drosera à feuilles rondes','Droseraceae','Drosera','Petite plante carnivore de tourbière acide, feuilles rondes en rosette à poils glanduleux rouges collants.']
  };
  const G={prairie:'Vérifier port, feuilles basales/caulinaires, inflorescence, floraison et cortège prairial.',humide:'Vérifier hydromorphie, joncs/carex, feuilles/tiges adaptées aux sols frais à engorgés.',carex:'Observer tige, gaine, épis, utricules mûrs, bec et glumes ; loupe indispensable.',juncus:'Observer tige, feuilles cloisonnées ou non, tépales, capsule et habitat humide.',hélophyte:'Vérifier enracinement dans vase/eau, tiges émergées, ceinture de mare/fossé/berge.',lande:'Observer sous-arbrisseau, feuilles petites/coriaces, acidiphilie, sol pauvre.',rudéral:'Chercher perturbation, enrichissement azoté, sol remanié, espèces nitrophiles.',invasive:'Noter densité, surface, reproduction et risque de dispersion.',orchidée:'Observer labelle, éperon, bractées, feuilles basales, fleur de face et profil.',tourbière:'Vérifier sphaignes, tourbe, eau acide, espèces oligotrophes.',bryophyte:'Observer substrat, humidité, architecture ; validation spécifique souvent délicate.',fougère:'Observer fronde, division du limbe, sores, pétiole, rhizome.'};
  function latinBase(p){return String(p.latin||'').replace(' agg.','').replace(/ · fiche locale .*/,'').trim()}
  function v(x){return x===undefined||x===null||x===''?'—':x}
  function verified(p){return V[latinBase(p)]||Object.values(V).find(a=>String(p.fr||'').startsWith(a[0]))}
  function enrich(p){const vv=verified(p);if(vv){p.fr=String(p.fr||'').includes('fiche locale')?vv[0]:p.fr;p.latin=latinBase(p);p.family=vv[1];p.criteria=vv[3];p.proStatus=p.detailed?'fiche vérifiée à consolider':'fiche modèle vérifiée à consolider'}const fam=F[p.family]||['—','—','Observer port, feuilles, tige, fleurs, fruits, pilosité, habitat et cortège.'];const gen=vv?vv[2]:latinBase(p).split(' ')[0]||'—';p.classif={regne:'Plantae',embranchement:p.family==='Sphagnaceae'?'Bryophytes':p.family==='Dennstaedtiaceae'?'Ptéridophytes':'Trachéophytes',clade:p.family==='Sphagnaceae'?'Bryophytes':p.family==='Dennstaedtiaceae'?'Ptéridophytes':'Angiospermes',classe:fam[0],ordre:fam[1],famille:p.family||'—',genre:gen,taxon:p.latin||p.fr||'—'};const groupCrit=G[p.group]||G[String(p.group||'').split(' ')[0]]||'Croiser morphologie, habitat, phénologie et cortège associé.';p.identification={synthese:p.criteria||fam[2],famille:fam[2],groupe:groupCrit,feuille:'Disposition, forme du limbe, marge, nervation, pétiole/gaine/stipules et pilosité.',tige:'Section, nœuds, pilosité, rameaux, rhizome ou stolon si visible.',fleur:'Inflorescence, symétrie, calice, corolle, étamines, ovaire et couleur.',fruit:'Type de fruit mûr, forme, mode d’ouverture, graines si visibles.',terrain:'Photographier port, feuille dessus/dessous, tige, fleur, fruit et habitat. Noter date, station et cortège.',validation:vv?'Classification et critères renseignés pour le taxon ; statuts à vérifier avec INPN/TAXREF/CBN.':'Critères par famille/groupe : à compléter par une flore pour validation spécifique.'};return p}
  if(window.DATA&&Array.isArray(DATA.plants))DATA.plants.forEach(enrich);
  window.openPlant=function(id){const p=enrich(DATA.plants.find(x=>x.id===id));const n=state.notes[id]||'',photos=state.photos[id]||[],c=p.classif,ic=p.identification;modalContent.innerHTML='<h2>'+v(p.fr)+'</h2><div class="latin">'+v(p.latin)+' · '+v(p.family)+'</div><div class="badges"><span class="badge">'+v(p.group)+'</span><span class="badge">'+v(p.proStatus)+'</span><span class="badge">'+v(p.eunis)+'</span><span class="badge">'+v(p.syntaxon)+'</span></div><section class="module"><h3>Classement taxonomique</h3><table><tr><th>Rang</th><th>Valeur</th></tr><tr><td>Règne</td><td>'+v(c.regne)+'</td></tr><tr><td>Embranchement</td><td>'+v(c.embranchement)+'</td></tr><tr><td>Clade</td><td>'+v(c.clade)+'</td></tr><tr><td>Classe</td><td>'+v(c.classe)+'</td></tr><tr><td>Ordre</td><td>'+v(c.ordre)+'</td></tr><tr><td>Famille</td><td>'+v(c.famille)+'</td></tr><tr><td>Genre</td><td>'+v(c.genre)+'</td></tr><tr><td>Taxon</td><td><i>'+v(c.taxon)+'</i></td></tr></table></section><h3>Galerie personnelle — 6 photos</h3><p>La photo 1 devient automatiquement la couverture.</p><div class="photo-grid">'+[0,1,2,3,4,5].map(i=>'<label class="photo-slot">'+(photos[i]?'<img src="'+photos[i]+'">':'Photo '+(i+1)+'<br>'+(i===0?'couverture':''))+'<input hidden type="file" accept="image/*" onchange="addPhoto('+id+','+i+',this)"></label>').join('')+'</div><section class="module"><h3>Critères d’identification</h3><table><tr><th>Bloc</th><th>À vérifier</th></tr><tr><td>Synthèse</td><td>'+v(ic.synthese)+'</td></tr><tr><td>Famille</td><td>'+v(ic.famille)+'</td></tr><tr><td>Groupe/habitat</td><td>'+v(ic.groupe)+'</td></tr><tr><td>Feuille</td><td>'+v(ic.feuille)+'</td></tr><tr><td>Tige</td><td>'+v(ic.tige)+'</td></tr><tr><td>Fleur</td><td>'+v(ic.fleur)+'</td></tr><tr><td>Fruit</td><td>'+v(ic.fruit)+'</td></tr><tr><td>Terrain</td><td>'+v(ic.terrain)+'</td></tr><tr><td>Validation</td><td>'+v(ic.validation)+'</td></tr></table></section><div class="two-col"><section class="module"><h3>Description</h3><p>'+v(p.description)+'</p><p><b>Habitat :</b> '+v(p.habitat)+'</p></section><section class="module"><h3>Écologie</h3><p>'+v(p.ecology)+'</p></section><section class="module"><h3>Confusions</h3><p>'+v(p.confusions)+'</p></section><section class="module"><h3>Niveau expert</h3><p>'+v(p.expert)+'</p></section></div><h3>Notes personnelles</h3><textarea id="note">'+n+'</textarea><div class="actions"><button class="primary" onclick="state.notes['+id+']=$(\'#note\').value;save();closeModal();render()">Sauvegarder</button><button class="secondary" onclick="removePhotos('+id+')">Retirer photos</button></div>';modal.showModal()};
  if(typeof render==='function')render();
})();