// Botadex lot 002 : graminées, carex, joncs, orchidées, fougères, boisements et milieux secs/humides.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
const rows=`
Fromental élevé|Arrhenatherum elatius|Poaceae|Poales|Monocotylédones|Prairies de fauche mésophiles, talus, bords de routes|E2|Arrhenatherion|Grande graminée de fauche, panicule lâche, feuilles larges, ligule bien visible|indicatrice prairie de fauche
Ray-grass anglais|Lolium perenne|Poaceae|Poales|Monocotylédones|Prairies pâturées, pelouses, chemins, gazons|E2|Cynosurion|Épi aplati, épillets appliqués contre l’axe, plante de pâture et piétinement|commune
Fétuque rouge|Festuca rubra|Poaceae|Poales|Monocotylédones|Prairies, pelouses, talus, sols plutôt pauvres|E2/E1|Cynosurion / Nardetea|Feuilles fines souvent enroulées, touffes, panicule discrète|commune
Fétuque élevée|Schedonorus arundinaceus|Poaceae|Poales|Monocotylédones|Prairies fraîches, fossés, bords de chemins|E2/E3|Arrhenatherion / Agrostietea|Grande graminée robuste, feuilles larges rudes, panicule dressée|commune
Pâturin annuel|Poa annua|Poaceae|Poales|Monocotylédones|Sols piétinés, chemins, jardins, trottoirs|J/E2|Polygono-Poetea annuae|Petite graminée, panicule courte, floraison quasi annuelle, sols tassés|commune
Pâturin des prés|Poa pratensis|Poaceae|Poales|Monocotylédones|Prairies, pelouses, talus, pâtures|E2|Cynosurion|Rhizomateux, feuilles à extrémité en capuchon, panicule pyramidale|commune
Agrostide stolonifère|Agrostis stolonifera|Poaceae|Poales|Monocotylédones|Prairies humides, berges, sols tassés frais|E3/C3|Agrostietea stoloniferae|Stolons rampants, panicule fine, feuilles étroites, milieux humides|indicatrice humide
Agrostide capillaire|Agrostis capillaris|Poaceae|Poales|Monocotylédones|Prairies maigres, landes, pelouses acides|E2/F4|Nardetea / Calluno-Ulicetea|Petite graminée à panicule fine ouverte, sols pauvres acides|indicatrice maigre acide
Canche cespiteuse|Deschampsia cespitosa|Poaceae|Poales|Monocotylédones|Prairies humides, bois frais, mégaphorbiaies|E3/G1|Calthion / Alnion|Grosses touffes, feuilles très rudes, panicule ample|indicatrice humide
Canche flexueuse|Avenella flexuosa|Poaceae|Poales|Monocotylédones|Bois acides, landes, sols pauvres siliceux|F4/G1|Quercion roboris|Feuilles très fines, panicule souple, sols acides forestiers|indicatrice acide
Brome mou|Bromus hordeaceus|Poaceae|Poales|Monocotylédones|Pelouses, friches, prairies sèches, chemins|E2/J|Stellarietea / Cynosurion|Épillets velus, panicule molle, plante annuelle commune|commune
Brome stérile|Anisantha sterilis|Poaceae|Poales|Monocotylédones|Friches, murs, talus secs, chemins|J/E5|Sisymbrietalia|Panicule très lâche pendante, longues arêtes, milieux secs rudéraux|commune
Chiendent rampant|Elytrigia repens|Poaceae|Poales|Monocotylédones|Friches, cultures, bords de chemins, prairies dégradées|J/E5|Agropyretalia|Rhizomes traçants, épi dressé, feuilles rudes, colonise les sols perturbés|commune
Vulpin des prés|Alopecurus pratensis|Poaceae|Poales|Monocotylédones|Prairies fraîches à humides de fauche|E2/E3|Arrhenatherion / Calthion|Inflorescence cylindrique douce, floraison printanière, prairies fraîches|indicatrice prairie fraîche
Fléole des prés|Phleum pratense|Poaceae|Poales|Monocotylédones|Prairies, talus, fauches, pâtures|E2|Arrhenatherion|Épi cylindrique dense, ligule longue, plante fourragère commune|commune
Brachypode des bois|Brachypodium sylvaticum|Poaceae|Poales|Monocotylédones|Bois frais, haies, lisières ombragées|G1/E5|Querco-Fagetea|Feuilles larges molles, épis arqués, graminée forestière|indicatrice bois frais
Brachypode penné|Brachypodium pinnatum|Poaceae|Poales|Monocotylédones|Pelouses sèches, ourlets calcicoles, talus|E1/E5|Mesobromion / Trifolion medii|Graminée rhizomateuse, feuilles raides, épis alternes|indicatrice pelouse sèche
Laîche hérissée|Carex hirta|Cyperaceae|Poales|Monocotylédones|Prairies fraîches, fossés, bords de chemins, sols enrichis|E3/E2|Agrostietea / Arrhenatherion|Laîche velue, épis espacés, feuilles pubescentes|commune
Laîche distique|Carex disticha|Cyperaceae|Poales|Monocotylédones|Prairies humides, fossés, marais, sols engorgés|E3|Caricion gracilis|Épi compact brun, tiges en colonies, prairies humides|indicatrice humide
Laîche des rives|Carex riparia|Cyperaceae|Poales|Monocotylédones|Berges, fossés, roselières, marais eutrophes|C3/D5|Magnocaricion|Grande laîche robuste, feuilles larges, épis cylindriques forts|indicatrice roselière
Laîche aiguë|Carex acuta|Cyperaceae|Poales|Monocotylédones|Prairies inondables, berges, fossés|E3/C3|Magnocaricion|Grande laîche de zones inondables, épis femelles pendants|indicatrice inondable
Laîche faux-souchet|Carex pseudocyperus|Cyperaceae|Poales|Monocotylédones|Bords de mares, fossés, bois marécageux|C3/G1|Magnocaricion|Épis verts pendants, aspect de souchet, milieux très humides|indicatrice humide
Laîche étoilée|Carex echinata|Cyperaceae|Poales|Monocotylédones|Prairies tourbeuses, bas-marais acides, suintements|D2/E3.4|Caricion fuscae|Petits épis étoilés, milieux oligotrophes acides|patrimoniale à vérifier
Jonc articulé|Juncus articulatus|Juncaceae|Poales|Monocotylédones|Fossés, vases, prairies humides, suintements|E3/C3|Nanocyperion / Agrostietea|Feuilles cloisonnées articulées, petite taille, sols humides ouverts|indicatrice humide
Jonc glauque|Juncus inflexus|Juncaceae|Poales|Monocotylédones|Fossés, prairies humides, sols tassés basiques|E3/J|Agrostietea|Tiges glauques raides, moelle interrompue, touffes robustes|commune humide
Jonc des crapauds|Juncus bufonius|Juncaceae|Poales|Monocotylédones|Ornières, vases exondées, sols nus humides|C3/J|Nanocyperion|Très petit jonc annuel, sols temporairement humides et ouverts|indicatrice vases
Luzule champêtre|Luzula campestris|Juncaceae|Poales|Monocotylédones|Pelouses, prairies maigres, talus acides|E2/E1|Nardetea / Cynosurion|Feuilles poilues en bordure, inflorescences brunâtres, sols pauvres|indicatrice maigre
Luzule des bois|Luzula sylvatica|Juncaceae|Poales|Monocotylédones|Bois frais acides, ravins, hêtraies-chênaies|G1|Querco-Fagetea|Grande luzule forestière, feuilles larges ciliées|indicatrice forestière
Fougère mâle|Dryopteris filix-mas|Dryopteridaceae|Polypodiales|Polypodiopsida|Bois frais, haies, talus ombragés|G1/E5|Querco-Fagetea|Grande fougère en touffe, sores arrondis, frondes divisées|commune
Fougère femelle|Athyrium filix-femina|Athyriaceae|Polypodiales|Polypodiopsida|Bois humides, fossés ombragés, suintements|G1/E3|Alnion / Querco-Fagetea|Frondes fines très divisées, aspect délicat, milieux frais|commune humide
Polypode commun|Polypodium vulgare|Polypodiaceae|Polypodiales|Polypodiopsida|Talus, murs, rochers, vieux arbres moussus|H3/G1|Asplenietea|Frondes simples pennées, sores ronds sans indusie|commune
Asplénium scolopendre|Asplenium scolopendrium|Aspleniaceae|Polypodiales|Polypodiopsida|Puits, murs humides, ravins, bois frais calcaires|H3/G1|Asplenietea|Frondes entières en langue, sores linéaires dessous|commune locale
Capillaire des murailles|Asplenium trichomanes|Aspleniaceae|Polypodiales|Polypodiopsida|Murs, rochers, vieux ponts, talus pierreux|H3|Asplenietea|Petite fougère à rachis noir et folioles arrondies|commune
Prêle des champs|Equisetum arvense|Equisetaceae|Equisetales|Equisetopsida|Champs, talus frais, fossés, sols remaniés|J/E3|Equisetalia|Tiges fertiles brunes puis tiges vertes stériles ramifiées|commune
Prêle des marais|Equisetum palustre|Equisetaceae|Equisetales|Equisetopsida|Prairies humides, marais, fossés|E3/D5|Calthion / Magnocaricion|Tiges vertes ramifiées, gaines dentées, milieux humides|indicatrice humide
Orchis pyramidal|Anacamptis pyramidalis|Orchidaceae|Asparagales|Monocotylédones|Pelouses sèches, talus calcaires, prairies maigres|E1/E2|Mesobromion|Inflorescence pyramidale rose, éperon fin, feuilles linéaires|patrimoniale à vérifier
Orchis mâle|Orchis mascula|Orchidaceae|Asparagales|Monocotylédones|Bois clairs, prairies maigres, lisières|E2/G1|Mesobromion / Querco-Fagetea|Fleurs pourpres, feuilles souvent tachetées, éperon dressé|patrimoniale à vérifier
Ophrys abeille|Ophrys apifera|Orchidaceae|Asparagales|Monocotylédones|Pelouses, talus, prairies maigres, friches calcaires|E1/E2|Mesobromion|Labelle brun velouté imitant une abeille, sépales roses|patrimoniale à vérifier
Ophrys araignée|Ophrys aranifera|Orchidaceae|Asparagales|Monocotylédones|Pelouses sèches, prairies maigres calcicoles|E1|Mesobromion|Ophrys précoce, labelle sombre, dessin variable, pelouses calcaires|patrimoniale à vérifier
Listère ovale|Neottia ovata|Orchidaceae|Asparagales|Monocotylédones|Bois frais, haies, prairies ombragées|G1/E2|Querco-Fagetea|Deux grandes feuilles opposées, fleurs verdâtres en épi|commune locale
Épipactis helléborine|Epipactis helleborine|Orchidaceae|Asparagales|Monocotylédones|Bois, lisières, parcs, haies ombragées|G1/FA|Querco-Fagetea|Orchidée verte-pourpre, feuilles ovales alternes, fleurs pendantes|commune locale
Primevère officinale|Primula veris|Primulaceae|Ericales|Eudicotylédones|Prairies maigres, talus, pelouses calcaires|E2/E1|Mesobromion|Fleurs jaunes en ombelle penchée, calice renflé, feuilles gaufrées|indicatrice prairie maigre
Primevère acaule|Primula vulgaris|Primulaceae|Ericales|Eudicotylédones|Bois frais, haies, talus ombragés|G1/E5|Fraxino-Quercion|Fleurs jaune pâle solitaires, rosette de feuilles gaufrées|commune
Jacinthe des bois|Hyacinthoides non-scripta|Asparagaceae|Asparagales|Monocotylédones|Bois frais, chênaies, haies anciennes|G1|Querco-Fagetea|Clochettes bleues pendantes d’un seul côté, feuilles rubanées|indicatrice bois ancien
Muguet|Convallaria majalis|Asparagaceae|Asparagales|Monocotylédones|Bois, lisières, sols frais à secs|G1|Querco-Fagetea|Deux feuilles larges, clochettes blanches odorantes, baies rouges|commune locale
Sceau-de-Salomon multiflore|Polygonatum multiflorum|Asparagaceae|Asparagales|Monocotylédones|Bois frais, haies, lisières ombragées|G1|Querco-Fagetea|Tige arquée, feuilles alternes, fleurs blanches pendantes par plusieurs|indicatrice forestière
Parisette à quatre feuilles|Paris quadrifolia|Melanthiaceae|Liliales|Monocotylédones|Bois frais anciens, sols humifères|G1|Querco-Fagetea|Quatre feuilles en verticille, fleur unique verdâtre, baie noire|patrimoniale à vérifier
Anémone des bois|Anemone nemorosa|Ranunculaceae|Ranunculales|Eudicotylédones|Bois frais, haies anciennes, chênaies|G1|Querco-Fagetea|Fleur blanche printanière, feuilles profondément découpées, tapis forestiers|indicatrice bois
Renoncule tête d'or|Ranunculus auricomus agg.|Ranunculaceae|Ranunculales|Eudicotylédones|Bois frais, prairies ombragées, haies|G1/E2|Querco-Fagetea|Fleurs jaunes parfois incomplètes, feuilles basales arrondies découpées|commune locale
Populage des marais|Caltha palustris|Ranunculaceae|Ranunculales|Eudicotylédones|Prairies humides, sources, fossés, marais|E3/D5|Calthion|Grosses fleurs jaunes brillantes, feuilles cordées luisantes, milieux très humides|indicatrice humide
Scirpe des bois|Scirpus sylvaticus|Cyperaceae|Poales|Monocotylédones|Prairies humides, fossés, bois marécageux|E3/G1|Calthion / Alnion|Grande Cyperaceae, inflorescence ramifiée, feuilles larges|indicatrice humide
Souchet brun|Cyperus fuscus|Cyperaceae|Poales|Monocotylédones|Vases exondées, berges, grèves humides|C3/J|Nanocyperion|Petit souchet annuel, inflorescences brunâtres, vases nues|indicatrice vases
Scirpe des marais|Eleocharis palustris|Cyperaceae|Poales|Monocotylédones|Bords de mares, fossés, marais, vases inondées|C3/D5|Eleocharitetalia|Tiges fines sans feuilles apparentes, épillet terminal unique|indicatrice amphibie
Baldellie fausse-renoncule|Baldellia ranunculoides|Alismataceae|Alismatales|Monocotylédones|Mares oligotrophes, berges sableuses humides|C3/D2|Littorelletea|Petite plante amphibie, fleurs rosées, feuilles en rosette|patrimoniale à vérifier
Flûteau nageant|Luronium natans|Alismataceae|Alismatales|Monocotylédones|Mares, fossés oligotrophes, eaux peu profondes|C1/C3|Littorelletea|Feuilles flottantes ovales, petites fleurs blanches, espèce protégée à vérifier|protégée potentielle à vérifier
Ache nodiflore|Helosciadium nodiflorum|Apiaceae|Apiales|Eudicotylédones|Ruisseaux, fossés, sources, eaux courantes lentes|C2/C3|Glycerio-Sparganion|Apiaceae aquatique rampante, feuilles pennées, petites ombelles|indicatrice aquatique
Cresson de fontaine|Nasturtium officinale|Brassicaceae|Brassicales|Eudicotylédones|Sources, ruisseaux, fossés à eau claire|C2|Glycerio-Sparganion|Feuilles composées charnues, fleurs blanches, plante aquatique comestible|indicatrice eau courante
Renoncule aquatique|Ranunculus aquatilis agg.|Ranunculaceae|Ranunculales|Eudicotylédones|Mares, fossés, eaux lentes ou temporaires|C1/C3|Ranunculion aquatilis|Feuilles flottantes lobées et feuilles submergées filiformes, fleurs blanches|aquatique à vérifier
Callitriche stagnale|Callitriche stagnalis|Plantaginaceae|Lamiales|Eudicotylédones|Mares, fossés, eaux calmes peu profondes|C1/C3|Callitricho-Batrachion|Petite aquatique à rosettes flottantes, identification spécifique délicate|aquatique commune
Menthe des champs|Mentha arvensis|Lamiaceae|Lamiales|Eudicotylédones|Prairies humides, cultures fraîches, fossés|E3/J|Agrostietea|Odeur de menthe, verticilles floraux axillaires, milieux frais|commune humide
Scutellaire casquée|Scutellaria galericulata|Lamiaceae|Lamiales|Eudicotylédones|Berges, fossés, roselières, bois humides|C3/E3|Phragmito-Magnocaricetea|Fleurs bleu violacé, calice à bosse, feuilles opposées|indicatrice humide
Lycope d'Europe|Lycopus europaeus|Lamiaceae|Lamiales|Eudicotylédones|Berges, fossés, roselières, prairies humides|C3/E3|Phragmito-Magnocaricetea|Feuilles opposées dentées, petites fleurs blanches ponctuées, sans odeur forte|indicatrice humide
Reine-des-bois|Aruncus dioicus|Rosaceae|Rosales|Eudicotylédones|Ravins frais, bois humides, berges ombragées|G1/E5|Adenostylion / milieux frais|Grande Rosaceae à panicules plumeuses blanches, feuilles composées|patrimoniale à vérifier
Sanicle d'Europe|Sanicula europaea|Apiaceae|Apiales|Eudicotylédones|Bois frais, hêtraies-chênaies, sols riches|G1|Fagetalia|Feuilles palmées luisantes, petites ombelles verdâtres, sous-bois frais|indicatrice forestière
Mercuriale vivace|Mercurialis perennis|Euphorbiaceae|Malpighiales|Eudicotylédones|Bois frais neutres à calcaires, haies anciennes|G1|Fagetalia|Tapis de sous-bois, feuilles opposées, fleurs verdâtres, plante dioïque|indicatrice forestière
Euphorbe réveille-matin|Euphorbia helioscopia|Euphorbiaceae|Malpighiales|Eudicotylédones|Cultures, jardins, friches, sols nus|J/I1|Stellarietea mediae|Ombelle vert jaunâtre, feuilles obovales, latex blanc irritant|commune
Euphorbe des bois|Euphorbia amygdaloides|Euphorbiaceae|Malpighiales|Eudicotylédones|Bois, haies, lisières ombragées|G1/E5|Querco-Fagetea|Feuilles persistantes en rosette terminale, bractées vert-jaune|commune forestière
Nerprun purgatif|Rhamnus cathartica|Rhamnaceae|Rosales|Eudicotylédones|Haies, fourrés, lisières calcicoles|F3/FA|Prunetalia|Arbuste épineux, feuilles opposées/subopposées, baies noires|commune locale
Viorne obier|Viburnum opulus|Viburnaceae|Dipsacales|Eudicotylédones|Haies humides, ripisylves, bois frais|F3/G1|Alnion / Prunetalia|Feuilles lobées opposées, inflorescences blanches, fruits rouges|commune humide
Viorne lantane|Viburnum lantana|Viburnaceae|Dipsacales|Eudicotylédones|Haies sèches, lisières calcicoles, fourrés|F3/FA|Prunetalia|Feuilles opposées velues, fruits rouges puis noirs|commune locale
Solidage du Canada|Solidago canadensis|Asteraceae|Asterales|Eudicotylédones|Friches, berges, talus, terrains remaniés|J/E5|Communautés invasives|Grandes tiges, panicules jaunes, colonies denses rhizomateuses|invasive à vérifier
Buddleia de David|Buddleja davidii|Scrophulariaceae|Lamiales|Eudicotylédones|Friches, murs, voies ferrées, remblais|J/E5|Communautés rudérales invasives|Arbuste à feuilles opposées, panicules violettes, milieux remaniés|invasive à surveiller
Raisin d'Amérique|Phytolacca americana|Phytolaccaceae|Caryophyllales|Eudicotylédones|Friches, lisières, coupes forestières, jardins abandonnés|J/E5|Communautés invasives|Grande plante, tiges rougeâtres, grappes de baies noir pourpre|invasive à surveiller
Vergerette du Canada|Erigeron canadensis|Asteraceae|Asterales|Eudicotylédones|Friches, trottoirs, cultures, sols nus secs|J/I1|Stellarietea mediae|Plante dressée, nombreux petits capitules, feuilles étroites|exotique naturalisée
Séneçon du Cap|Senecio inaequidens|Asteraceae|Asterales|Eudicotylédones|Bords de routes, friches, voies ferrées, terrains secs|J/E5|Communautés rudérales|Fleurs jaunes, feuilles linéaires, floraison longue, exotique envahissant|invasive à vérifier
Ailante glanduleux|Ailanthus altissima|Simaroubaceae|Sapindales|Eudicotylédones|Friches, talus, villes, bords de route|J/F3|Communautés invasives|Grand arbre, feuilles composées très grandes, odeur désagréable, drageons|invasive à vérifier
Robinier faux-acacia|Robinia pseudoacacia|Fabaceae|Fabales|Eudicotylédones|Talus, boisements, friches, sols secs enrichis|G1/F3|Robinietea|Arbre épineux, feuilles composées, grappes blanches parfumées, gousses|exotique envahissant à vérifier
Herbe de la pampa|Cortaderia selloana|Poaceae|Poales|Monocotylédones|Friches, talus, jardins, zones littorales ou remaniées|J/E5|Communautés invasives|Très grande touffe, feuilles coupantes, grands plumeaux blancs|invasive à vérifier
`.trim().split('\n');
let next=Math.max(...DATA.plants.map(p=>p.id||0))+1;
rows.forEach(r=>{let a=r.split('|');if(DATA.plants.some(p=>p.latin===a[1]))return;DATA.plants.push({id:next++,fr:a[0],latin:a[1],family:a[2],classif:{ordre:a[3],classe:a[4],famille:a[2]},biotope:a[5],habitat:a[5],eunis:a[6],syntaxon:a[7],criteria:a[8],status:a[9]||'commune',confusions:'À vérifier avec flore locale si doute.',ecology:a[5]})});
DATA.plants.sort((a,b)=>a.fr.localeCompare(b.fr,'fr')).forEach((p,i)=>p.id=i+1);
})();
