// Botadex lot 003 : messicoles, rudérales, alluviales, boisements, prairies et plantes à statut à vérifier.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
const rows=`
Bleuet des champs|Cyanus segetum|Asteraceae|Asterales|Eudicotylédones|Moissons, cultures extensives, bords de champs|I1/J|Stellarietea mediae|Capitules bleus, bractées ciliées, plante messicole des cultures|messicole patrimoniale à vérifier
Nielle des blés|Agrostemma githago|Caryophyllaceae|Caryophyllales|Eudicotylédones|Moissons, cultures céréalières extensives, sols remués|I1/J|Stellarietea mediae|Grande Caryophyllaceae, fleurs pourpres, calice à longues dents|messicole rare à vérifier
Miroir de Vénus|Legousia speculum-veneris|Campanulaceae|Asterales|Eudicotylédones|Moissons, vignes, champs calcaires ou neutres|I1/J|Stellarietea mediae|Petites fleurs violettes en étoile, capsule allongée, plante messicole|messicole patrimoniale à vérifier
Peigne de Vénus|Scandix pecten-veneris|Apiaceae|Apiales|Eudicotylédones|Moissons, cultures, sols calcaires remués|I1/J|Stellarietea mediae|Apiaceae annuelle, fruits très longs en becs parallèles|messicole patrimoniale à vérifier
Adonis d'automne|Adonis annua|Ranunculaceae|Ranunculales|Eudicotylédones|Moissons calcaires, cultures extensives|I1/J|Stellarietea mediae|Fleurs rouges, feuilles très découpées, plante messicole rare|messicole rare à vérifier
Pied-d'alouette royal|Consolida regalis|Ranunculaceae|Ranunculales|Eudicotylédones|Moissons, cultures calcaires, sols remués|I1/J|Stellarietea mediae|Fleurs bleues à long éperon, feuilles très divisées|messicole patrimoniale à vérifier
Gesse tubéreuse|Lathyrus tuberosus|Fabaceae|Fabales|Eudicotylédones|Champs, talus, friches, bords de cultures|I1/E5|Stellarietea / Trifolion medii|Fleurs roses parfumées, feuilles à vrilles, tubercules souterrains|commune locale
Vesce hérissée|Vicia hirsuta|Fabaceae|Fabales|Eudicotylédones|Cultures, friches, talus, prairies ouvertes|I1/E2|Stellarietea mediae|Petite vesce, fleurs pâles par deux, gousses velues|commune
Vesce à quatre graines|Vicia tetrasperma|Fabaceae|Fabales|Eudicotylédones|Prairies, haies, cultures, friches|E2/I1|Arrhenatheretalia|Petite vesce grêle, fleurs pâles, gousses à peu de graines|commune
Trèfle douteux|Trifolium dubium|Fabaceae|Fabales|Eudicotylédones|Pelouses, prairies, chemins, sols pauvres|E2/E1|Cynosurion|Très petit trèfle jaune, folioles petites, capitules lâches|commune
Trèfle des champs|Trifolium campestre|Fabaceae|Fabales|Eudicotylédones|Pelouses sèches, talus, friches ouvertes|E1/E2|Sedo-Scleranthetea / Cynosurion|Capitules jaunes dorés devenant bruns, folioles denticulées|commune sèche
Trèfle intermédiaire|Trifolium medium|Fabaceae|Fabales|Eudicotylédones|Ourlets, lisières, prairies peu intensives|E5/E2|Trifolion medii|Capitules roses, feuilles trifoliées, plante d’ourlets mésophiles|indicatrice ourlet
Sainfoin cultivé|Onobrychis viciifolia|Fabaceae|Fabales|Eudicotylédones|Talus calcaires, pelouses, prairies semées|E1/E2|Mesobromion|Fleurs roses striées en grappes, feuilles pennées, gousses dentées|commune locale
Luzerne lupuline|Medicago lupulina|Fabaceae|Fabales|Eudicotylédones|Pelouses, prairies, chemins, sols secs|E2/E1|Cynosurion|Petites fleurs jaunes en grappes compactes, fruits noirs réniformes|commune
Luzerne cultivée|Medicago sativa|Fabaceae|Fabales|Eudicotylédones|Bords de routes, prairies semées, friches sèches|E2/E5|Arrhenatheretalia|Fleurs violettes, feuilles trifoliées, gousse spiralée|commune/naturalisée
Mélilot officinal|Melilotus officinalis|Fabaceae|Fabales|Eudicotylédones|Friches, remblais, talus, bords de routes|E5/J|Dauco-Melilotion|Grande Fabaceae à grappes jaunes, odeur de coumarine au séchage|commune rudérale
Mélilot blanc|Melilotus albus|Fabaceae|Fabales|Eudicotylédones|Friches, berges remaniées, talus secs|E5/J|Dauco-Melilotion|Grande Fabaceae à grappes blanches, feuilles trifoliées|commune rudérale
Ononis épineux|Ononis spinosa|Fabaceae|Fabales|Eudicotylédones|Pelouses sèches, prairies maigres, talus calcaires|E1/E2|Mesobromion|Sous-arbrisseau épineux, fleurs roses papilionacées|indicatrice pelouse sèche
Genêt à balais|Cytisus scoparius|Fabaceae|Fabales|Eudicotylédones|Landes, talus acides, lisières, coupes forestières|F4/E5|Calluno-Ulicetea|Arbuste vert anguleux, fleurs jaunes, gousses noires|indicatrice acide
Ajonc d'Europe|Ulex europaeus|Fabaceae|Fabales|Eudicotylédones|Landes, haies, talus acides, friches|F4/F3|Calluno-Ulicetea|Arbuste très épineux, fleurs jaunes, milieux acides atlantiques|commune acide
Ajonc nain|Ulex minor|Fabaceae|Fabales|Eudicotylédones|Landes humides ou fraîches, sols acides pauvres|F4/D1|Ericion tetralicis|Petit ajonc, fleurs jaunes, landes atlantiques humides|indicatrice lande humide
Bruyère cendrée|Erica cinerea|Ericaceae|Ericales|Eudicotylédones|Landes sèches acides, talus siliceux, lisières|F4|Calluno-Ulicetea|Fleurs pourpres en grelots, feuilles verticillées par 3|indicatrice lande sèche
Myrtille|Vaccinium myrtillus|Ericaceae|Ericales|Eudicotylédones|Bois acides, landes fraîches, sols pauvres|G1/F4|Quercion roboris|Sous-arbrisseau à tiges vertes anguleuses, baies bleues|indicatrice acide
Gaillet mou|Galium mollugo agg.|Rubiaceae|Gentianales|Eudicotylédones|Prairies, talus, ourlets, lisières|E2/E5|Arrhenatheretalia|Feuilles verticillées, panicules de petites fleurs blanches|commune
Gaillet des marais|Galium palustre|Rubiaceae|Gentianales|Eudicotylédones|Fossés, prairies humides, roselières, berges|E3/C3|Phragmito-Magnocaricetea|Gaillet grêle des milieux humides, feuilles verticillées étroites|indicatrice humide
Gaillet aquatique|Galium uliginosum|Rubiaceae|Gentianales|Eudicotylédones|Prairies humides, bas-marais, suintements|E3/D2|Molinion / Caricion|Gaillet de milieux pauvres humides, feuilles verticillées rudes|indicatrice humide maigre
Rubéole des champs|Sherardia arvensis|Rubiaceae|Gentianales|Eudicotylédones|Cultures, pelouses ouvertes, sols remaniés|I1/E1|Stellarietea mediae|Petite Rubiaceae, feuilles verticillées, petites fleurs lilas|commune
Garance voyageuse|Rubia peregrina|Rubiaceae|Gentianales|Eudicotylédones|Haies, lisières, chênaies thermophiles|F3/G1|Quercetea ilicis local / Prunetalia|Liane rude à feuilles coriaces verticillées, fruits noirs|commune locale thermophile
Torilis du Japon|Torilis japonica|Apiaceae|Apiales|Eudicotylédones|Ourlets, haies, friches, lisières|E5/F3|Galio-Urticetea|Petite Apiaceae à fruits accrochants, ombelles discrètes|commune
Grande ciguë|Conium maculatum|Apiaceae|Apiales|Eudicotylédones|Friches riches, fossés, bords de chemins, berges eutrophes|E5/J|Artemisietea|Grande Apiaceae toxique, tige tachetée de pourpre, odeur désagréable|commune toxique
Cerfeuil penché|Chaerophyllum temulum|Apiaceae|Apiales|Eudicotylédones|Haies, lisières, ourlets nitrophiles|E5/G1|Galio-Urticetea|Apiaceae velue, tiges tachées, ombelles blanches|commune
Œnanthe safranée|Oenanthe crocata|Apiaceae|Apiales|Eudicotylédones|Fossés, ruisseaux, berges, prairies humides|E3/C2|Oenanthion crocatae|Grande Apiaceae très toxique, racines tubérisées, milieux humides|indicatrice humide toxique
Œnanthe fistuleuse|Oenanthe fistulosa|Apiaceae|Apiales|Eudicotylédones|Prairies inondables, mares temporaires, fossés|E3/C3|Oenanthion fistulosae|Tiges creuses fistuleuses, ombelles blanches, milieux longuement humides|patrimoniale à vérifier
Angélique sauvage|Angelica sylvestris|Apiaceae|Apiales|Eudicotylédones|Mégaphorbiaies, fossés, bois humides, prairies fraîches|E5/E3|Filipendulion|Grande Apiaceae, tige souvent violacée, ombelles rosées blanches|indicatrice humide
Valériane officinale|Valeriana officinalis|Caprifoliaceae|Dipsacales|Eudicotylédones|Fossés, mégaphorbiaies, prairies humides, berges|E5/E3|Filipendulion|Feuilles composées opposées, fleurs roses pâles parfumées|indicatrice humide
Valériane dioïque|Valeriana dioica|Caprifoliaceae|Dipsacales|Eudicotylédones|Bas-marais, prairies humides maigres, suintements|E3.4/D2|Caricion / Molinion|Petite valériane dioïque, feuilles basales ovales, milieux humides pauvres|patrimoniale à vérifier
Cabaret des oiseaux|Dipsacus fullonum|Caprifoliaceae|Dipsacales|Eudicotylédones|Friches fraîches, fossés, bords de chemins, prairies humides|E5/E3|Dipsacion|Grandes tiges épineuses, feuilles soudées retenant l’eau, capitules épineux|commune
Succise des bois|Knautia dipsacifolia|Caprifoliaceae|Dipsacales|Eudicotylédones|Lisières fraîches, bois clairs, prairies montagnardes localisées|G1/E5|Querco-Fagetea|Capitules lilas, feuilles opposées, espèce à vérifier localement|patrimoniale à vérifier
Pulmonaire officinale|Pulmonaria officinalis agg.|Boraginaceae|Boraginales|Eudicotylédones|Bois frais, haies, lisières ombragées|G1/E5|Fagetalia|Feuilles souvent tachées de blanc, fleurs roses puis bleues|commune locale
Buglosse officinale|Anchusa officinalis|Boraginaceae|Boraginales|Eudicotylédones|Friches sèches, talus, bords de routes|E5/J|Dauco-Melilotion|Boraginaceae hérissée, fleurs bleu violacé, feuilles rugueuses|commune locale
Cynoglosse officinale|Cynoglossum officinale|Boraginaceae|Boraginales|Eudicotylédones|Friches sèches, talus, bords de chemins|E5/J|Onopordetalia|Plante grisâtre velue, fleurs pourpres sombres, fruits accrochants|commune locale
Épervière piloselle|Pilosella officinarum|Asteraceae|Asterales|Eudicotylédones|Pelouses sèches, talus, landes ouvertes, sols pauvres|E1/E2|Nardetea / Sedo-Scleranthetea|Rosette velue blanchâtre dessous, stolons, capitules jaunes solitaires|indicatrice maigre
Épervière des murs|Hieracium murorum|Asteraceae|Asterales|Eudicotylédones|Bois clairs, talus ombragés, lisières acides|G1/E5|Querco-Fagetea|Rosette de feuilles dentées, capitules jaunes, tige peu feuillée|commune forestière
Séneçon commun|Senecio vulgaris|Asteraceae|Asterales|Eudicotylédones|Jardins, cultures, friches, sols nus|J/I1|Stellarietea mediae|Petits capitules jaunes sans ligules visibles, aigrettes blanches|commune
Armoise commune|Artemisia vulgaris|Asteraceae|Asterales|Eudicotylédones|Friches, talus, bords de routes, sols riches|E5/J|Artemisietea|Feuilles vertes dessus blanchâtres dessous, odeur aromatique, tiges hautes|commune rudérale
Tanaisie commune|Tanacetum vulgare|Asteraceae|Asterales|Eudicotylédones|Bords de routes, friches, berges, talus|E5/J|Artemisietea|Capitules jaunes sans ligules en boutons, feuilles très découpées aromatiques|commune
Achillée sternutatoire|Achillea ptarmica|Asteraceae|Asterales|Eudicotylédones|Prairies humides, fossés, mégaphorbiaies ouvertes|E3|Calthion|Capitules blancs assez grands, feuilles étroites dentées, milieux humides|indicatrice humide
Gnaphale des marais|Gnaphalium uliginosum|Asteraceae|Asterales|Eudicotylédones|Vases exondées, chemins humides, cultures mouillées|C3/J|Nanocyperion|Petite annuelle grisâtre laineuse, capitules brunâtres, sols humides nus|indicatrice vases
Cotonière commune|Filago vulgaris|Asteraceae|Asterales|Eudicotylédones|Pelouses sèches, friches sableuses, sols pauvres ouverts|E1/J|Sedo-Scleranthetea|Petite plante laineuse, capitules groupés, milieux secs ouverts|indicatrice pelouse sèche
Spargoute des champs|Spergula arvensis|Caryophyllaceae|Caryophyllales|Eudicotylédones|Cultures sableuses, sols acides, friches ouvertes|I1/E1|Scleranthion annui|Feuilles filiformes verticillées, fleurs blanches, sols sableux acides|messicole/acidiphile
Scléranthe annuel|Scleranthus annuus|Caryophyllaceae|Caryophyllales|Eudicotylédones|Pelouses sèches, cultures pauvres, sols sableux acides|E1/I1|Sedo-Scleranthetea|Petites touffes vert jaunâtre, fleurs sans pétales apparents|indicatrice sol pauvre acide
Sagine couchée|Sagina procumbens|Caryophyllaceae|Caryophyllales|Eudicotylédones|Sols piétinés, trottoirs, chemins humides, murs|J/H3|Polygono-Poetea|Petite plante en coussin, feuilles opposées fines, petites fleurs blanches|commune urbaine
Spergulaire rouge|Spergularia rubra|Caryophyllaceae|Caryophyllales|Eudicotylédones|Chemins sableux, sols tassés, graviers, milieux secs ouverts|J/E1|Saginetea / Sedo-Scleranthetea|Petites fleurs roses, feuilles linéaires, stipules scarieuses|commune
Arenaire serpolet|Arenaria serpyllifolia|Caryophyllaceae|Caryophyllales|Eudicotylédones|Murs, sols secs, pelouses ouvertes, cultures|H3/E1|Sedo-Scleranthetea|Petite annuelle, feuilles opposées, fleurs blanches, sépales marqués|commune sèche
Cymbalaire hépatique|Kickxia spuria|Plantaginaceae|Lamiales|Eudicotylédones|Cultures, vignes, sols calcaires remaniés|I1/J|Stellarietea mediae|Petites fleurs jaune-violet à éperon, feuilles ovales, messicole|messicole à vérifier
Linaire élatine|Kickxia elatine|Plantaginaceae|Lamiales|Eudicotylédones|Cultures, champs, sols remués|I1/J|Stellarietea mediae|Fleurs bicolores à éperon, feuilles hastées, plante couchée|messicole à vérifier
Plantain majeur|Plantago major|Plantaginaceae|Lamiales|Eudicotylédones|Chemins, pelouses piétinées, cours, sols tassés|J/E2|Polygono-Poetea|Rosette à feuilles larges, nervures parallèles, longs épis verdâtres|commune
Plantain moyen|Plantago media|Plantaginaceae|Lamiales|Eudicotylédones|Prairies maigres, pelouses, talus calcaires|E2/E1|Mesobromion / Cynosurion|Rosette appliquée, feuilles ovales velues, épis à étamines lilas|indicatrice prairie maigre
Plantain corne-de-cerf|Plantago coronopus|Plantaginaceae|Lamiales|Eudicotylédones|Chemins sablonneux, pelouses ouvertes, bords salés localement|E1/J|Saginetea / milieux ouverts|Feuilles très découpées en rosette, épis courts|commune locale
Centaurée noire|Centaurea nigra|Asteraceae|Asterales|Eudicotylédones|Prairies maigres, talus, lisières, sols acides à neutres|E2/E5|Cynosurion / Arrhenatherion|Capitules pourpres, bractées noires frangées, plante prairiale|indicatrice prairie
Centaurée scabieuse|Centaurea scabiosa|Asteraceae|Asterales|Eudicotylédones|Pelouses sèches, talus calcaires, prairies maigres|E1/E2|Mesobromion|Grande centaurée, feuilles découpées, capitules pourpres, bractées noires|indicatrice pelouse sèche
Campanule raiponce|Campanula rapunculus|Campanulaceae|Asterales|Eudicotylédones|Talus, prairies sèches, ourlets, bords de chemins|E2/E5|Arrhenatheretalia|Fleurs bleues en cloche, tige dressée, feuilles basales allongées|commune locale
Campanule à feuilles rondes|Campanula rotundifolia|Campanulaceae|Asterales|Eudicotylédones|Pelouses sèches, landes, talus pauvres|E1/F4|Sedo-Scleranthetea / Nardetea|Petites clochettes bleues, feuilles basales rondes souvent disparues|indicatrice maigre
Jasione des montagnes|Jasione montana|Campanulaceae|Asterales|Eudicotylédones|Pelouses sableuses acides, landes sèches, talus pauvres|E1/F4|Sedo-Scleranthetea|Capitules bleus, feuilles étroites ondulées, sols sableux acides|indicatrice acide sèche
Hélianthème nummulaire|Helianthemum nummularium|Cistaceae|Malvales|Eudicotylédones|Pelouses calcaires, talus secs, landes sèches basiques|E1|Mesobromion|Sous-arbrisseau, fleurs jaunes, feuilles opposées, milieux secs|indicatrice pelouse sèche
Petite pimprenelle|Poterium sanguisorba|Rosaceae|Rosales|Eudicotylédones|Pelouses sèches, prairies maigres, talus calcaires|E1/E2|Mesobromion|Feuilles composées, folioles dentées, têtes florales verdâtres rougeâtres|indicatrice pelouse sèche
Pimprenelle officinale|Sanguisorba officinalis|Rosaceae|Rosales|Eudicotylédones|Prairies humides à fraîches, fauches peu intensives|E3/E2|Molinion / Calthion|Inflorescences ovoïdes rouge sombre, feuilles composées|indicatrice prairie humide
Alchémille commune|Alchemilla vulgaris agg.|Rosaceae|Rosales|Eudicotylédones|Prairies fraîches, talus, bords de chemins|E2/E3|Arrhenatheretalia|Feuilles arrondies plissées retenant l’eau, petites fleurs vert-jaune|commune à vérifier
Fragonnette petit-houx|Ruscus aculeatus|Asparagaceae|Asparagales|Monocotylédones|Bois, haies anciennes, lisières ombragées|G1/F3|Querco-Fagetea|Cladodes piquants semblant être des feuilles, baies rouges|commune locale
Frêne à feuilles étroites|Fraxinus angustifolia|Oleaceae|Lamiales|Eudicotylédones|Ripisylves, boisements alluviaux, vallées de Loire|G1/C2|Fraxino-Ulmenion|Feuilles composées plus étroites, arbre alluvial, à vérifier localement|alluvial à vérifier
Peuplier noir|Populus nigra|Salicaceae|Malpighiales|Eudicotylédones|Berges, ripisylves, grèves alluviales de Loire|G1/C2|Salicion albae|Grand arbre, feuilles triangulaires, bourgeons visqueux, milieu alluvial|patrimonial alluvial à vérifier
Peuplier tremble|Populus tremula|Salicaceae|Malpighiales|Eudicotylédones|Bois clairs, lisières, coupes, sols frais|G1/E5|Populion tremulae|Feuilles rondes à long pétiole aplati tremblant au vent|commune
Peuplier blanc|Populus alba|Salicaceae|Malpighiales|Eudicotylédones|Berges, ripisylves, boisements alluviaux|G1/C2|Populion albae|Feuilles blanches tomenteuses dessous, tronc clair, drageonnant|alluvial
Saule marsault|Salix caprea|Salicaceae|Malpighiales|Eudicotylédones|Haies, bois clairs, friches fraîches, lisières|F3/G1|Salicion capreae|Feuilles ovales larges, chatons précoces, arbuste pionnier|commune
Saule fragile|Salix fragilis|Salicaceae|Malpighiales|Eudicotylédones|Berges, ripisylves, fossés, bords de Loire|G1/C2|Salicion albae|Rameaux cassants, feuilles lancéolées, grand saule de berge|alluvial
Saule pourpre|Salix purpurea|Salicaceae|Malpighiales|Eudicotylédones|Berges, grèves, fourrés alluviaux|F9/C3|Salicion triandrae|Rameaux pourpres, feuilles opposées/subopposées vers l’extrémité|alluvial
Bouleau verruqueux|Betula pendula|Betulaceae|Fagales|Eudicotylédones|Landes, bois clairs, friches, sols acides|G1/F4|Betulion / Quercion|Écorce blanche, rameaux pendants, feuilles triangulaires dentées|commune acide
Châtaignier|Castanea sativa|Fagaceae|Fagales|Eudicotylédones|Bois acides, haies, taillis, sols siliceux|G1|Quercion roboris|Feuilles longues dentées, bogues épineuses, sols acides|commune acide
Hêtre|Fagus sylvatica|Fagaceae|Fagales|Eudicotylédones|Bois frais, pentes ombragées, haies anciennes localement|G1|Fagetalia|Feuilles ovales ciliées jeunes, écorce grise lisse, faînes|forestière locale
Houx|Ilex aquifolium|Aquifoliaceae|Aquifoliales|Eudicotylédones|Bois, haies anciennes, lisières ombragées|G1/F3|Ilici-Quercetum local|Feuilles persistantes coriaces épineuses, baies rouges|commune forestière
If commun|Taxus baccata|Taxaceae|Pinales|Gymnospermes|Bois, haies, vieux parcs, coteaux ombragés|G3/G1|Taxo-Fagion local|Conifère à aiguilles plates, arilles rouges, toxique|patrimonial à vérifier
Pin maritime|Pinus pinaster|Pinaceae|Pinales|Gymnospermes|Plantations, landes, sols sableux acides|G3/F4|Pinetea / plantations|Aiguilles longues par deux, gros cônes, écorce épaisse|planté/naturalisé
Pin sylvestre|Pinus sylvestris|Pinaceae|Pinales|Gymnospermes|Plantations, landes sèches, sols pauvres|G3/F4|Pinetea|Aiguilles par deux, écorce orangée en haut du tronc|planté/naturalisé
`.trim().split('\n');
let next=Math.max(...DATA.plants.map(p=>p.id||0))+1;
rows.forEach(r=>{let a=r.split('|');if(DATA.plants.some(p=>p.latin===a[1]))return;DATA.plants.push({id:next++,fr:a[0],latin:a[1],family:a[2],classif:{ordre:a[3],classe:a[4],famille:a[2]},biotope:a[5],habitat:a[5],eunis:a[6],syntaxon:a[7],criteria:a[8],status:a[9]||'commune',confusions:'À vérifier avec flore locale si doute.',ecology:a[5]})});
DATA.plants.sort((a,b)=>a.fr.localeCompare(b.fr,'fr')).forEach((p,i)=>p.id=i+1);
})();
