// Botadex lot 005 : complément prairies, friches, aquatiques, alluviales et exotiques à surveiller.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
const rows=`
Épiaire droite|Stachys recta|Lamiaceae|Lamiales|Eudicotylédones|Pelouses sèches, talus calcaires, ourlets thermophiles|E1/E5|Mesobromion / Trifolion medii|Lamiaceae dressée à fleurs jaune pâle, feuilles opposées crénelées|indicatrice pelouse sèche
Germandrée petit-chêne|Teucrium chamaedrys|Lamiaceae|Lamiales|Eudicotylédones|Pelouses sèches, coteaux, lisières calcicoles|E1/E5|Mesobromion|Sous-arbrisseau, feuilles crénelées, fleurs roses, milieux secs|indicatrice pelouse sèche
Ballote noire|Ballota nigra|Lamiaceae|Lamiales|Eudicotylédones|Villages, friches, haies nitrophiles, bords de chemins|E5/J|Artemisietea|Lamiaceae malodorante, fleurs pourpres, feuilles opposées gaufrées|commune rudérale
Marrube blanc|Marrubium vulgare|Lamiaceae|Lamiales|Eudicotylédones|Friches sèches, talus, vieux murs, sols riches secs|E5/J|Onopordetalia|Plante blanchâtre laineuse, feuilles rondes crénelées, fleurs en verticilles|rudérale sèche
Cataire|Nepeta cataria|Lamiaceae|Lamiales|Eudicotylédones|Friches, vieux murs, bords de villages, sols secs riches|E5/J|Artemisietea|Plante aromatique grisâtre, fleurs blanchâtres ponctuées, odeur de menthe|commune locale
Mélisse officinale|Melissa officinalis|Lamiaceae|Lamiales|Eudicotylédones|Jardins naturalisés, haies, ourlets frais|E5/J|Galio-Urticetea|Odeur citronnée, feuilles opposées gaufrées, fleurs pâles|naturalisée commune
Verveine officinale|Verbena officinalis|Verbenaceae|Lamiales|Eudicotylédones|Chemins, friches, prairies sèches, lieux piétinés|J/E2|Plantaginetea / Artemisietea|Tiges carrées, petits épis grêles de fleurs lilas pâle|commune
Millepertuis couché|Hypericum humifusum|Hypericaceae|Malpighiales|Eudicotylédones|Sols nus humides ou sableux, chemins, landes ouvertes|J/E1|Nanocyperion / Sedo-Scleranthetea|Petite plante couchée, fleurs jaunes, feuilles opposées ponctuées|commune acide
Millepertuis à quatre ailes|Hypericum tetrapterum|Hypericaceae|Malpighiales|Eudicotylédones|Fossés, prairies humides, suintements|E3|Agrostietea / Calthion|Tige à quatre ailes, fleurs jaunes, feuilles ponctuées, milieux humides|indicatrice humide
Millepertuis élégant|Hypericum pulchrum|Hypericaceae|Malpighiales|Eudicotylédones|Landes, lisières acides, talus pauvres|F4/E5|Calluno-Ulicetea|Fleurs jaunes petites, boutons rougeâtres, feuilles opposées, sol acide|indicatrice acide
Chardon penché|Carduus nutans|Asteraceae|Asterales|Eudicotylédones|Friches sèches, pâtures, talus, sols perturbés|E5/J|Onopordetalia|Gros capitules pourpres penchés, feuilles épineuses|commune sèche
Chardon crépu|Carduus crispus|Asteraceae|Asterales|Eudicotylédones|Ourlets nitrophiles, haies, bords de rivières, friches fraîches|E5/G1|Galio-Urticetea|Chardon à tiges ailées épineuses, capitules pourpres plus petits|commune
Laitue sauvage|Lactuca serriola|Asteraceae|Asterales|Eudicotylédones|Friches, trottoirs, talus, sols secs rudéraux|J/E5|Sisymbrietalia|Feuilles verticales épineuses sur la nervure, capitules jaunes|commune rudérale
Salsifis des prés|Tragopogon pratensis|Asteraceae|Asterales|Eudicotylédones|Prairies, talus, bords de chemins, fauches|E2|Arrhenatherion|Capitules jaunes, bractées longues, akènes à aigrette plumeuse|commune
Inule conyze|Inula conyzae|Asteraceae|Asterales|Eudicotylédones|Lisières sèches, coteaux, ourlets, friches calcicoles|E5/E1|Trifolion medii|Capitules brunâtres sans ligules nettes, plante dressée velue|indicatrice ourlet sec
Pulicaire commune|Pulicaria vulgaris|Asteraceae|Asterales|Eudicotylédones|Vases exondées, mares temporaires, chemins humides|C3/J|Nanocyperion|Petite annuelle jaunâtre de vases humides, à distinguer de P. dysenterica|patrimoniale à vérifier
Érigéron annuel|Erigeron annuus|Asteraceae|Asterales|Eudicotylédones|Friches, berges, bords de routes, prairies perturbées|J/E5|Communautés rudérales|Capitules nombreux à ligules blanches fines, plante exotique naturalisée|exotique à surveiller
Vergerette de Sumatra|Erigeron sumatrensis|Asteraceae|Asterales|Eudicotylédones|Trottoirs, friches, cultures, sols secs remaniés|J/I1|Stellarietea mediae|Grande vergerette dressée, capitules petits, feuilles étroites|exotique commune
Amarante hybride|Amaranthus hybridus|Amaranthaceae|Caryophyllales|Eudicotylédones|Cultures, friches chaudes, jardins, sols riches|J/I1|Stellarietea mediae|Amarante robuste, inflorescences vertes, plante estivale rudérale|exotique naturalisée
Amarante livide|Amaranthus blitum|Amaranthaceae|Caryophyllales|Eudicotylédones|Jardins, friches, sols piétinés ou riches|J/I1|Stellarietea mediae|Amarante basse à feuilles souvent échancrées, fleurs vertes|commune rudérale
Pourpier maraîcher|Portulaca oleracea|Portulacaceae|Caryophyllales|Eudicotylédones|Sols nus chauds, jardins, trottoirs, cultures|J/I1|Stellarietea mediae|Plante charnue rampante, feuilles succulentes, fleurs jaunes discrètes|commune chaude
Renouée des oiseaux|Polygonum aviculare|Polygonaceae|Caryophyllales|Eudicotylédones|Chemins, trottoirs, cours, sols tassés|J|Polygono-Poetea annuae|Plante couchée, petites feuilles, ochréas, milieux piétinés|commune
Renouée amphibie|Persicaria amphibia|Polygonaceae|Caryophyllales|Eudicotylédones|Mares, fossés, berges, prairies inondables|C1/C3|Potamion / Bidention|Forme aquatique flottante ou terrestre, épis roses|indicatrice humide
Patience d'eau|Rumex hydrolapathum|Polygonaceae|Caryophyllales|Eudicotylédones|Berges, roselières, fossés, marais|C3/D5|Magnocaricion|Très grande patience des bords d’eau, feuilles longues|indicatrice roselière
Patience agglomérée|Rumex conglomeratus|Polygonaceae|Caryophyllales|Eudicotylédones|Fossés, prairies humides, chemins frais|E3/J|Agrostietea|Petite patience ramifiée, fruits en glomérules espacés|commune humide
Écuelle d'eau|Hydrocotyle vulgaris|Araliaceae|Apiales|Eudicotylédones|Prairies tourbeuses, fossés, suintements, landes humides|D2/E3.4|Hydrocotylo-Baldellion|Feuilles rondes peltées, plante rampante de milieux humides pauvres|indicatrice humide pauvre
Samole de Valerand|Samolus valerandi|Primulaceae|Ericales|Eudicotylédones|Suintements, vases humides, bords de mares, parfois basiques|C3/D2|Samolo-Littorelletea|Petites fleurs blanches, rosette, milieux humides ouverts|patrimoniale à vérifier
Hottonie des marais|Hottonia palustris|Primulaceae|Ericales|Eudicotylédones|Mares, fossés, eaux calmes végétalisées|C1/C3|Hottonion palustris|Feuilles submergées finement divisées, fleurs lilas émergées|patrimoniale à vérifier
Utriculaire commune|Utricularia vulgaris agg.|Lentibulariaceae|Lamiales|Eudicotylédones|Mares, fossés, eaux stagnantes pauvres à mésotrophes|C1/D2|Utricularion|Plante carnivore aquatique sans racines, fleurs jaunes, utricules|patrimoniale à vérifier
Petite utriculaire|Utricularia minor|Lentibulariaceae|Lamiales|Eudicotylédones|Tourbières, gouilles, mares acides pauvres|D1/D2|Utricularion minoris|Très petite utriculaire aquatique, milieux oligotrophes acides|patrimoniale à vérifier
Littorelle à une fleur|Littorella uniflora|Plantaginaceae|Lamiales|Eudicotylédones|Grèves exondées oligotrophes, mares et étangs pauvres|C3/D2|Littorelletea|Petite rosette amphibie, feuilles linéaires charnues|protégée potentielle à vérifier
Pilulaire globuleuse|Pilularia globulifera|Marsileaceae|Salviniales|Ptéridophytes|Mares temporaires, grèves humides, landes humides|C3/D2|Isoeto-Nanojuncetea|Petite fougère à feuilles filiformes, sporocarpes globuleux|protégée potentielle à vérifier
Marsilée à quatre feuilles|Marsilea quadrifolia|Marsileaceae|Salviniales|Ptéridophytes|Mares, boires, eaux calmes alluviales|C1/C3|Marsileion|Fougère aquatique à quatre folioles comme un trèfle|protégée potentielle à vérifier
Cératophylle immergé|Ceratophyllum demersum|Ceratophyllaceae|Ceratophyllales|Angiospermes|Eaux stagnantes eutrophes, mares, fossés|C1|Ceratophyllion|Plante submergée sans racines, feuilles verticillées fourchues rudes|aquatique commune
Myriophylle en épi|Myriophyllum spicatum|Haloragaceae|Saxifragales|Eudicotylédones|Eaux calmes à lentes, étangs, rivières|C1/C2|Potamion|Feuilles submergées finement divisées en verticilles, épis émergés|aquatique commune
Myriophylle verticillé|Myriophyllum verticillatum|Haloragaceae|Saxifragales|Eudicotylédones|Mares, étangs, eaux calmes riches en végétation|C1|Potamion|Feuilles verticillées finement découpées, bractées visibles à l’inflorescence|aquatique à vérifier
Callitriche des eaux stagnantes|Callitriche obtusangula|Plantaginaceae|Lamiales|Eudicotylédones|Fossés, ruisseaux lents, eaux stagnantes|C1/C2|Callitricho-Batrachion|Callitriche à rosettes flottantes, détermination fine des fruits|aquatique à vérifier
Glycérie flottante|Glyceria fluitans|Poaceae|Poales|Monocotylédones|Fossés, ruisseaux, mares, prairies inondées|C2/C3|Glycerio-Sparganion|Graminée aquatique, panicule lâche, feuilles flottantes possibles|indicatrice aquatique
Glycérie aquatique|Glyceria maxima|Poaceae|Poales|Monocotylédones|Berges, fossés, roselières, eaux peu profondes|C3/D5|Glycerietum maximae|Grande graminée hélophyte, feuilles larges, peuplements denses|indicatrice roselière
Rubanier simple|Sparganium emersum|Typhaceae|Poales|Monocotylédones|Rivières lentes, fossés, eaux peu profondes|C2/C3|Glycerio-Sparganion|Rubanier à feuilles flottantes/émergées, têtes globuleuses espacées|aquatique à vérifier
Scirpe maritime|Bolboschoenus maritimus|Cyperaceae|Poales|Monocotylédones|Fossés, marais, berges vaseuses, eaux parfois minéralisées|C3/D5|Bolboschoenion|Cyperaceae robuste, inflorescence brunâtre, tubercules|indicatrice marais
Souchet comestible|Cyperus esculentus|Cyperaceae|Poales|Monocotylédones|Cultures, berges remaniées, friches humides chaudes|J/C3|Communautés invasives localisées|Souchet à ombelle, tubercules, espèce exotique adventice|invasive/adventice à vérifier
Paspale dilaté|Paspalum dilatatum|Poaceae|Poales|Monocotylédones|Prairies humides, bords de routes, pelouses chaudes|E2/J|Cynosurion perturbé|Graminée exotique, épis digités, milieux chauds humides|exotique à surveiller
Paspale à deux épis|Paspalum distichum|Poaceae|Poales|Monocotylédones|Berges vaseuses, gazons humides, fossés|C3/J|Communautés amphibies perturbées|Graminée rampante à deux épis, colonise sols humides|invasive à vérifier
Vigne-vierge commune|Parthenocissus inserta|Vitaceae|Vitales|Eudicotylédones|Murs, haies, boisements rudéraux, friches urbaines|J/F3|Communautés rudérales|Liane exotique à feuilles composées, vrilles, fruits bleutés|exotique naturalisée
Vigne-vierge vraie|Parthenocissus quinquefolia|Vitaceae|Vitales|Eudicotylédones|Murs, jardins, haies, friches|J/F3|Communautés rudérales|Liane à cinq folioles, vrilles à crampons, fruits bleus|exotique à surveiller
Lyciet commun|Lycium barbarum|Solanaceae|Solanales|Eudicotylédones|Haies, friches sèches, talus, vieux murs|F3/J|Prunetalia rudéral|Arbuste épineux, fleurs violettes, baies rouges allongées|exotique naturalisé
Mahonia faux-houx|Mahonia aquifolium|Berberidaceae|Ranunculales|Eudicotylédones|Bois urbains, haies, parcs, lisières rudérales|G1/J|Communautés rudérales|Arbuste persistant à feuilles piquantes composées, fleurs jaunes|exotique à surveiller
Laurier-cerise|Prunus laurocerasus|Rosaceae|Rosales|Eudicotylédones|Haies plantées, bois urbains, lisières ombragées|F3/G1|Communautés horticoles naturalisées|Feuilles persistantes coriaces, grappes blanches, fruits noirs|exotique à surveiller
Sumac vinaigrier|Rhus typhina|Anacardiaceae|Sapindales|Eudicotylédones|Talus, friches, jardins abandonnés, sols secs|J/F3|Communautés rudérales|Arbuste drageonnant, feuilles composées, infrutescences rouges|exotique à surveiller
`.trim().split('\n');
let next=Math.max(...DATA.plants.map(p=>p.id||0))+1;
rows.forEach(r=>{let a=r.split('|');if(DATA.plants.some(p=>p.latin===a[1]))return;DATA.plants.push({id:next++,fr:a[0],latin:a[1],family:a[2],classif:{ordre:a[3],classe:a[4],famille:a[2]},biotope:a[5],habitat:a[5],eunis:a[6],syntaxon:a[7],criteria:a[8],status:a[9]||'commune',confusions:'À vérifier avec flore locale si doute.',ecology:a[5]})});
DATA.plants.sort((a,b)=>a.fr.localeCompare(b.fr,'fr')).forEach((p,i)=>p.id=i+1);
})();
