// Botadex lot 001 : ajout progressif de vraies plantes communes/indicatrices autour d'Angers.
(function(){
if(!window.DATA||!Array.isArray(DATA.plants))return;
const rows=`
Érable champêtre|Acer campestre|Sapindaceae|Sapindales|Eudicotylédones|Haies, lisières, bois clairs, bocage|F3/G1|Prunetalia / Carpino-Fagetea|Feuilles opposées lobées, samares par deux, petit arbre de haie|commune
Érable sycomore|Acer pseudoplatanus|Sapindaceae|Sapindales|Eudicotylédones|Bois frais, haies, friches arborées|G1/F3|Fraxino-Quercion|Grandes feuilles opposées palmées, samares pendantes, écorce en plaques|commune
Érable negundo|Acer negundo|Sapindaceae|Sapindales|Eudicotylédones|Berges, friches alluviales, ripisylves perturbées|G1/C3|Salicion albae perturbé|Feuilles composées opposées, samares, arbre exotique de milieux alluviaux|invasive à surveiller
Tilleul à petites feuilles|Tilia cordata|Malvaceae|Malvales|Eudicotylédones|Bois frais, haies, parcs, lisières|G1/FA|Carpino-Fagetea|Feuilles cordées petites, bractée membraneuse portant les fruits|commune
Orme champêtre|Ulmus minor|Ulmaceae|Rosales|Eudicotylédones|Haies, lisières, ripisylves, boisements alluviaux|G1/FA|Fraxino-Ulmenion|Feuilles asymétriques à la base, double denture, samares|commune
Sureau noir|Sambucus nigra|Viburnaceae|Dipsacales|Eudicotylédones|Haies, friches, lisières, sols riches|F3/E5|Prunetalia / Galio-Urticetea|Arbuste à grandes feuilles composées, corymbes blancs, baies noires|commune
Cornouiller sanguin|Cornus sanguinea|Cornaceae|Cornales|Eudicotylédones|Haies, fourrés, lisières calcicoles à neutres|F3/FA|Prunetalia|Feuilles opposées à nervures arquées, rameaux rouges, fruits noirs|commune
Fusain d'Europe|Euonymus europaeus|Celastraceae|Celastrales|Eudicotylédones|Haies, fourrés, lisières|F3/FA|Prunetalia|Rameaux verts, feuilles opposées, fruits roses à graines orangées|commune
Troène commun|Ligustrum vulgare|Oleaceae|Lamiales|Eudicotylédones|Haies, lisières, fourrés secs à mésophiles|F3/FA|Prunetalia|Arbuste à feuilles opposées entières, fleurs blanches, baies noires|commune
Lierre grimpant|Hedera helix|Araliaceae|Apiales|Eudicotylédones|Bois, haies, murs, vieux arbres|G1/F3|Hedero-Quercetalia|Liane ligneuse, feuilles persistantes lobées puis entières, fruits noirs|commune
Chèvrefeuille des bois|Lonicera periclymenum|Caprifoliaceae|Dipsacales|Eudicotylédones|Haies, bois, lisières, fourrés|F3/G1|Prunetalia / Quercetea|Liane à feuilles opposées, fleurs parfumées, baies rouges|commune
Houblon|Humulus lupulus|Cannabaceae|Rosales|Eudicotylédones|Haies humides, ripisylves, mégaphorbiaies|E5/G1|Convolvuletalia / Filipendulion|Liane herbacée rude, feuilles opposées lobées, cônes femelles|commune
Bryone dioïque|Bryonia dioica|Cucurbitaceae|Cucurbitales|Eudicotylédones|Haies, ourlets, friches, lisières|E5/F3|Galio-Urticetea|Vrilles, feuilles palmées, fleurs verdâtres, baies rouges toxiques|commune
Clématite des haies|Clematis vitalba|Ranunculaceae|Ranunculales|Eudicotylédones|Haies, lisières, fourrés, friches calcicoles|F3/E5|Prunetalia|Liane ligneuse, feuilles opposées composées, fruits plumeux|commune
Géranium herbe-à-Robert|Geranium robertianum|Geraniaceae|Geraniales|Eudicotylédones|Murs, haies, bois frais, talus ombragés|G1/E5|Geranion robertiani|Feuilles très découpées, odeur forte, fleurs roses, fruits en bec|commune
Géranium mou|Geranium molle|Geraniaceae|Geraniales|Eudicotylédones|Pelouses, chemins, friches ouvertes|E2/J|Stellarietea mediae|Petite plante velue, feuilles arrondies lobées, petites fleurs roses|commune
Géranium découpé|Geranium dissectum|Geraniaceae|Geraniales|Eudicotylédones|Cultures, friches, bords de chemins|J/I1|Stellarietea mediae|Feuilles très profondément découpées, petites fleurs roses|commune
Bec-de-grue commun|Erodium cicutarium|Geraniaceae|Geraniales|Eudicotylédones|Pelouses sèches, friches, sols sableux ou remaniés|E1/J|Sedo-Scleranthetea / Stellarietea|Feuilles pennées, fleurs roses, fruit à long bec spiralé|commune
Berce commune|Heracleum sphondylium|Apiaceae|Apiales|Eudicotylédones|Prairies fraîches, fossés, lisières, friches|E2/E5|Arrhenatherion / Aegopodion|Grande Apiaceae velue, feuilles larges lobées, ombelles blanches|commune
Carotte sauvage|Daucus carota|Apiaceae|Apiales|Eudicotylédones|Talus, prairies sèches, friches, bords de routes|E2/E5|Dauco-Melilotion|Ombelle blanche souvent à fleur centrale pourpre, bractées très découpées|commune
Anthrisque sauvage|Anthriscus sylvestris|Apiaceae|Apiales|Eudicotylédones|Haies, fossés, ourlets frais, bords de chemins|E5/G1|Aegopodion|Ombelles blanches, feuilles finement divisées, plante haute de printemps|commune
Égopode podagraire|Aegopodium podagraria|Apiaceae|Apiales|Eudicotylédones|Ourlets frais, haies, jardins, sous-bois eutrophes|E5/G1|Aegopodion podagrariae|Feuilles divisées en folioles ovales dentées, ombelles blanches|commune
Bardane commune|Arctium lappa|Asteraceae|Asterales|Eudicotylédones|Friches, talus, bords de chemins, sols riches|E5/J|Artemisietea|Très grandes feuilles, capitules à bractées crochues, fruits accrocheurs|commune
Cirse des champs|Cirsium arvense|Asteraceae|Asterales|Eudicotylédones|Cultures, friches, prairies enrichies|J/E5|Artemisietea / Stellarietea|Chardon rhizomateux, capitules lilas, feuilles épineuses|commune
Cirse commun|Cirsium vulgare|Asteraceae|Asterales|Eudicotylédones|Friches, pâtures, talus, sols perturbés|E5/J|Onopordetalia|Chardon robuste très épineux, capitules pourpres solitaires|commune
Cirse des marais|Cirsium palustre|Asteraceae|Asterales|Eudicotylédones|Prairies humides, mégaphorbiaies, fossés|E3/E5|Calthion / Filipendulion|Chardon haut à tige ailée épineuse, capitules pourpres groupés|indicatrice humide
Laiteron maraîcher|Sonchus oleraceus|Asteraceae|Asterales|Eudicotylédones|Jardins, cultures, friches, sols nus|J/I1|Stellarietea mediae|Feuilles molles embrassantes, capitules jaunes, latex blanc|commune
Laiteron rude|Sonchus asper|Asteraceae|Asterales|Eudicotylédones|Cultures, friches, trottoirs, sols riches|J/I1|Stellarietea mediae|Feuilles luisantes épineuses, oreillettes arrondies embrassantes|commune
Lampsane commune|Lapsana communis|Asteraceae|Asterales|Eudicotylédones|Haies, friches, bois clairs, sols riches|E5/G1|Galio-Urticetea|Capitules jaunes petits, feuilles inférieures lyrées, plante souple|commune
Porcelle enracinée|Hypochaeris radicata|Asteraceae|Asterales|Eudicotylédones|Prairies maigres, pelouses, talus|E2/E1|Cynosurion / Nardetea|Rosette plaquée, feuilles hérissées, capitules jaunes sur hampes ramifiées|commune
Crépide capillaire|Crepis capillaris|Asteraceae|Asterales|Eudicotylédones|Pelouses, prairies, friches sèches|E2/E5|Arrhenatheretalia|Capitules jaunes, tiges fines ramifiées, akènes à aigrette|commune
Marguerite commune|Leucanthemum vulgare|Asteraceae|Asterales|Eudicotylédones|Prairies, talus, fauches peu intensives|E2|Arrhenatherion|Grand capitule blanc à centre jaune, feuilles alternes dentées|commune
Matricaire inodore|Tripleurospermum inodorum|Asteraceae|Asterales|Eudicotylédones|Cultures, friches, sols remaniés|J/I1|Stellarietea mediae|Capitules blancs, feuilles très divisées, réceptacle plein|commune
Camomille sauvage|Matricaria chamomilla|Asteraceae|Asterales|Eudicotylédones|Cultures, friches, chemins, sols ouverts|J/I1|Stellarietea mediae|Odeur aromatique, feuilles très divisées, réceptacle conique creux|commune
Pulicaire dysentérique|Pulicaria dysenterica|Asteraceae|Asterales|Eudicotylédones|Fossés, prairies humides, bords de mares|E3/E5|Agrostietea / Filipendulion|Capitules jaunes, feuilles embrassantes, plante de milieux humides|indicatrice humide
Bident tripartite|Bidens tripartita|Asteraceae|Asterales|Eudicotylédones|Vases exondées, berges, fossés eutrophes|C3/J|Bidention tripartitae|Feuilles opposées souvent trilobées, akènes à arêtes crochues|indicatrice vases
Eupatoire chanvrine|Eupatorium cannabinum|Asteraceae|Asterales|Eudicotylédones|Mégaphorbiaies, fossés, berges, bois humides|E5/E3|Filipendulion|Feuilles opposées divisées, corymbes rosés, milieux humides riches|indicatrice humide
Salicaire commune|Lythrum salicaria|Lythraceae|Myrtales|Eudicotylédones|Berges, fossés, prairies humides, roselières|E3/C3|Lythrion / Filipendulion|Tige quadrangulaire, feuilles opposées, longs épis pourpres|indicatrice humide
Épilobe hirsute|Epilobium hirsutum|Onagraceae|Myrtales|Eudicotylédones|Fossés, berges, mégaphorbiaies eutrophes|E5/C3|Convolvuletalia / Filipendulion|Grande plante velue, fleurs roses, feuilles opposées dentées|indicatrice humide eutrophe
Épilobe à petites fleurs|Epilobium parviflorum|Onagraceae|Myrtales|Eudicotylédones|Fossés, suintements, berges, friches humides|E3/E5|Epilobion hirsuti|Fleurs roses petites, tige pubescente, capsules longues|commune humide
Onagre bisannuelle|Oenothera biennis|Onagraceae|Myrtales|Eudicotylédones|Friches, talus, remblais, bords de Loire|J/E5|Dauco-Melilotion|Grandes fleurs jaunes du soir, rosette puis tige, fruits allongés|exotique naturalisée
Lysimaque commune|Lysimachia vulgaris|Primulaceae|Ericales|Eudicotylédones|Fossés, prairies humides, mégaphorbiaies|E3/E5|Filipendulion|Fleurs jaunes en panicule, feuilles opposées ou verticillées|indicatrice humide
Lysimaque nummulaire|Lysimachia nummularia|Primulaceae|Ericales|Eudicotylédones|Prairies humides, berges, suintements, bois frais|E3/G1|Agrostietea / Alnion|Tiges rampantes, feuilles rondes opposées, fleurs jaunes solitaires|indicatrice humide
Mouron rouge|Lysimachia arvensis|Primulaceae|Ericales|Eudicotylédones|Cultures, jardins, vignes, sols nus|J/I1|Stellarietea mediae|Petite plante à feuilles opposées, fleurs rouges ou bleues, capsule globuleuse|commune
Véronique petit-chêne|Veronica chamaedrys|Plantaginaceae|Lamiales|Eudicotylédones|Prairies, haies, lisières, talus|E2/E5|Arrhenatheretalia|Fleurs bleues, feuilles opposées dentées, deux lignes de poils sur la tige|commune
Véronique de Perse|Veronica persica|Plantaginaceae|Lamiales|Eudicotylédones|Cultures, jardins, sols remaniés|J/I1|Stellarietea mediae|Fleurs bleues solitaires, feuilles dentées, plante couchée|commune
Véronique des ruisseaux|Veronica beccabunga|Plantaginaceae|Lamiales|Eudicotylédones|Ruisseaux, fossés, suintements, bords d’eau|C2/C3|Glycerio-Sparganion|Tiges charnues, feuilles opposées luisantes, fleurs bleues, milieu aquatique|indicatrice aquatique
Digitale pourpre|Digitalis purpurea|Plantaginaceae|Lamiales|Eudicotylédones|Coupes, landes, lisières acides, talus|E5/F4|Epilobietea / Calluno-Ulicetea|Grande hampe de fleurs pourpres en tubes, feuilles basales velues|commune acide
Linaire commune|Linaria vulgaris|Plantaginaceae|Lamiales|Eudicotylédones|Friches, talus, bords de routes, sols secs|E5/J|Dauco-Melilotion|Fleurs jaunes à éperon, feuilles linéaires alternes, tige dressée|commune
Scrofulaire noueuse|Scrophularia nodosa|Scrophulariaceae|Lamiales|Eudicotylédones|Bois frais, fossés, mégaphorbiaies, haies|G1/E5|Galio-Urticetea|Tige carrée, feuilles opposées, petites fleurs brunâtres|commune
Molène bouillon-blanc|Verbascum thapsus|Scrophulariaceae|Lamiales|Eudicotylédones|Friches sèches, talus, remblais, sols nus|E5/J|Onopordetalia|Grande plante tomenteuse blanchâtre, fleurs jaunes en épi dense|commune
Bugle rampante|Ajuga reptans|Lamiaceae|Lamiales|Eudicotylédones|Prairies fraîches, bois clairs, chemins humides|E2/G1|Cynosurion / Querco-Fagetea|Rosette, stolons, fleurs bleues en épi, feuilles opposées|commune
Épiaire des bois|Stachys sylvatica|Lamiaceae|Lamiales|Eudicotylédones|Bois frais, haies humides, ourlets|G1/E5|Galio-Urticetea|Grande Lamiaceae malodorante, feuilles opposées cordées, fleurs pourpres|commune
Bétoine officinale|Betonica officinalis|Lamiaceae|Lamiales|Eudicotylédones|Prairies maigres, landes, lisières, sols pauvres|E2/F4|Molinion / Nardetea|Feuilles basales crénelées, épi pourpre, milieux maigres|indicatrice maigre
Germandrée scorodoine|Teucrium scorodonia|Lamiaceae|Lamiales|Eudicotylédones|Landes, bois acides, talus siliceux|F4/G1|Quercion roboris|Feuilles gaufrées, odeur, fleurs jaunâtres en grappes unilatérales|indicatrice acide
Sauge des prés|Salvia pratensis|Lamiaceae|Lamiales|Eudicotylédones|Pelouses sèches, prairies maigres, talus calcaires|E1/E2|Mesobromion|Grandes fleurs bleu violacé bilabiées, feuilles basales rugueuses|indicatrice pelouse
Rumex oseille|Rumex acetosa|Polygonaceae|Caryophyllales|Eudicotylédones|Prairies, talus, bords de chemins|E2|Arrhenatherion|Feuilles sagittées, inflorescences rougeâtres, saveur acide|commune
Rumex à feuilles obtuses|Rumex obtusifolius|Polygonaceae|Caryophyllales|Eudicotylédones|Prairies enrichies, friches, sols tassés|E5/J|Rumicion obtusifolii|Grandes feuilles basales obtuses, panicules de fruits, sols riches|nitrophile
Patience crépue|Rumex crispus|Polygonaceae|Caryophyllales|Eudicotylédones|Friches, prairies humides, sols perturbés|E5/J|Rumicion|Feuilles ondulées crispées, panicule de fruits brunâtres|commune
Petite oseille|Rumex acetosella|Polygonaceae|Caryophyllales|Eudicotylédones|Pelouses sèches acides, landes, sols sableux|E1/F4|Sedo-Scleranthetea|Petite plante à feuilles hastées, sols pauvres acides|indicatrice acide
Renouée persicaire|Persicaria maculosa|Polygonaceae|Caryophyllales|Eudicotylédones|Fossés, cultures, vases, sols humides remaniés|J/C3|Bidention / Stellarietea|Feuilles avec tache sombre fréquente, épis roses, ochréa ciliée|commune humide
Renouée poivre-d'eau|Persicaria hydropiper|Polygonaceae|Caryophyllales|Eudicotylédones|Berges, fossés, vases humides|C3/J|Bidention tripartitae|Goût poivré, feuilles lancéolées, épis grêles verdâtres rosés|indicatrice vases
Renouée du Japon|Reynoutria japonica|Polygonaceae|Caryophyllales|Eudicotylédones|Berges, talus, friches, remblais|J/C3|Communautés invasives|Grandes tiges creuses, feuilles larges tronquées, rhizomes puissants|invasive avérée à vérifier
Chénopode blanc|Chenopodium album|Amaranthaceae|Caryophyllales|Eudicotylédones|Cultures, jardins, friches, sols nus riches|J/I1|Stellarietea mediae|Feuilles farineuses, inflorescences verdâtres, plante rudérale|commune
Arroche étalée|Atriplex patula|Amaranthaceae|Caryophyllales|Eudicotylédones|Cultures, friches, bords de chemins, sols riches|J/I1|Stellarietea mediae|Feuilles triangulaires hastées, fleurs verdâtres, bractéoles fructifères|commune
Amarante réfléchie|Amaranthus retroflexus|Amaranthaceae|Caryophyllales|Eudicotylédones|Cultures, friches chaudes, sols remaniés|J/I1|Stellarietea mediae|Inflorescences vertes denses, tige robuste, feuilles ovales|exotique naturalisée
Alliaire officinale|Alliaria petiolata|Brassicaceae|Brassicales|Eudicotylédones|Haies, ourlets, bois frais, sols riches|E5/G1|Galio-Urticetea|Feuilles odeur d’ail, fleurs blanches à 4 pétales, siliques longues|commune
Capselle bourse-à-pasteur|Capsella bursa-pastoris|Brassicaceae|Brassicales|Eudicotylédones|Cultures, trottoirs, jardins, sols nus|J/I1|Stellarietea mediae|Petites fleurs blanches, fruits triangulaires en cœur|commune
Cardamine des prés|Cardamine pratensis|Brassicaceae|Brassicales|Eudicotylédones|Prairies humides, fossés, bords de ruisseaux|E3|Calthion|Fleurs lilas pâle, feuilles composées, prairies humides printanières|indicatrice humide
Cardamine hérissée|Cardamine hirsuta|Brassicaceae|Brassicales|Eudicotylédones|Jardins, murs, sols nus, friches fraîches|J/G1|Stellarietea mediae|Petite Brassicaceae, siliques dressées, feuilles en rosette|commune
Moutarde des champs|Sinapis arvensis|Brassicaceae|Brassicales|Eudicotylédones|Cultures, friches, bords de champs|I1/J|Stellarietea mediae|Fleurs jaunes à 4 pétales, siliques, feuilles rudes|commune
Cymbalaire des murs|Cymbalaria muralis|Plantaginaceae|Lamiales|Eudicotylédones|Murs, vieux bâtiments, rocailles urbaines|H3/J|Parietarietea|Petites feuilles arrondies lobées, fleurs lilas à éperon|commune urbaine
Mauve sylvestre|Malva sylvestris|Malvaceae|Malvales|Eudicotylédones|Friches, bords de chemins, villages, sols riches|E5/J|Artemisietea|Fleurs mauves veinées, feuilles arrondies lobées, fruits en fromageon|commune
Mauve musquée|Malva moschata|Malvaceae|Malvales|Eudicotylédones|Prairies, talus, pelouses, bords de chemins|E2/E5|Arrhenatheretalia|Fleurs roses, feuilles supérieures très découpées, odeur légère|commune
Chélidoine|Chelidonium majus|Papaveraceae|Ranunculales|Eudicotylédones|Murs, haies, friches ombragées, sols riches|E5/J|Galio-Urticetea|Latex jaune orangé, fleurs jaunes à 4 pétales, feuilles lobées|commune
Coquelicot|Papaver rhoeas|Papaveraceae|Ranunculales|Eudicotylédones|Cultures, friches, sols remaniés|I1/J|Stellarietea mediae|Grandes fleurs rouges, latex, capsule arrondie|commune
Fumeterre officinale|Fumaria officinalis|Papaveraceae|Ranunculales|Eudicotylédones|Cultures, vignes, jardins, sols nus|I1/J|Stellarietea mediae|Feuilles très divisées, fleurs roses tubuleuses, plante glauque|commune
Violette odorante|Viola odorata|Violaceae|Malpighiales|Eudicotylédones|Haies, jardins, bois frais, ourlets|G1/E5|Fraxino-Quercion|Feuilles cordées, fleurs violettes odorantes, stolons|commune
Violette de Rivin|Viola riviniana|Violaceae|Malpighiales|Eudicotylédones|Bois clairs, haies, talus, pelouses acides|G1/E2|Querco-Fagetea|Fleurs violettes, éperon clair, feuilles cordées|commune
Pensée des champs|Viola arvensis|Violaceae|Malpighiales|Eudicotylédones|Cultures, friches, sols nus|I1/J|Stellarietea mediae|Petites fleurs jaunâtres blanchâtres, stipules découpées|commune
Consoude officinale|Symphytum officinale|Boraginaceae|Boraginales|Eudicotylédones|Fossés, prairies humides, berges, haies fraîches|E3/E5|Filipendulion|Grande plante rude, feuilles décurrentes, fleurs en cloche violettes ou crème|indicatrice humide
Vipérine commune|Echium vulgare|Boraginaceae|Boraginales|Eudicotylédones|Talus secs, friches, pelouses ouvertes|E1/E5|Dauco-Melilotion|Plante hérissée, fleurs bleues, étamines saillantes rouges|commune sèche
Myosotis des champs|Myosotis arvensis|Boraginaceae|Boraginales|Eudicotylédones|Cultures, friches, prairies sèches|I1/E2|Stellarietea mediae|Petites fleurs bleues, plante velue, inflorescence scorpioïde|commune
Myosotis des marais|Myosotis scorpioides|Boraginaceae|Boraginales|Eudicotylédones|Fossés, berges, prairies très humides|C3/E3|Glycerio-Sparganion|Fleurs bleues, plante de bord d’eau, feuilles allongées|indicatrice humide
Morelle noire|Solanum nigrum|Solanaceae|Solanales|Eudicotylédones|Cultures, jardins, friches, sols riches|J/I1|Stellarietea mediae|Petites fleurs blanches, baies noires, feuilles ovales|commune
Compagnon blanc|Silene latifolia|Caryophyllaceae|Caryophyllales|Eudicotylédones|Friches, talus, cultures, bords de chemins|E5/J|Artemisietea|Fleurs blanches, calice renflé, feuilles opposées velues|commune
Stellaire holostée|Stellaria holostea|Caryophyllaceae|Caryophyllales|Eudicotylédones|Haies, lisières, bois clairs|G1/E5|Querco-Fagetea|Grandes fleurs blanches à pétales fendus, feuilles opposées lancéolées|commune
Céraiste commun|Cerastium fontanum|Caryophyllaceae|Caryophyllales|Eudicotylédones|Prairies, pelouses, chemins|E2/J|Cynosurion|Petite plante velue, fleurs blanches, feuilles opposées|commune
Saponaire officinale|Saponaria officinalis|Caryophyllaceae|Caryophyllales|Eudicotylédones|Berges, friches fraîches, talus, alluvions|E5/C3|Convolvuletalia|Fleurs roses pâles, feuilles opposées, plante robuste souvent en colonie|commune
Typha à larges feuilles|Typha latifolia|Typhaceae|Poales|Monocotylédones|Mares, fossés, roselières, eaux stagnantes|D5/C3|Typhetum latifoliae|Grand hélophyte, feuilles larges, épi brun compact|indicatrice roselière
Typha à feuilles étroites|Typha angustifolia|Typhaceae|Poales|Monocotylédones|Mares, étangs, fossés, roselières|D5/C3|Typhetum angustifoliae|Feuilles plus étroites, épis mâle et femelle séparés par un intervalle|indicatrice roselière
Rubanier dressé|Sparganium erectum|Typhaceae|Poales|Monocotylédones|Fossés, mares, ruisseaux lents|C3/D5|Glycerio-Sparganion|Feuilles rubanées, inflorescences en têtes globuleuses|indicatrice aquatique
Plantain d'eau|Alisma plantago-aquatica|Alismataceae|Alismatales|Monocotylédones|Bords de mares, fossés, vases humides|C3/D5|Eleocharitetalia|Feuilles ovales émergées, panicule de petites fleurs rosées|indicatrice aquatique
Butome en ombelle|Butomus umbellatus|Butomaceae|Alismatales|Monocotylédones|Berges, fossés, eaux calmes|C3|Phragmito-Magnocaricetea|Ombelle de fleurs roses, feuilles linéaires triangulaires|patrimoniale à vérifier
Sagittaire|Sagittaria sagittifolia|Alismataceae|Alismatales|Monocotylédones|Fossés, rivières lentes, vases inondées|C3|Sagittarion|Feuilles sagittées émergées, fleurs blanches, plante aquatique|patrimoniale à vérifier
Potamot nageant|Potamogeton natans|Potamogetonaceae|Alismatales|Monocotylédones|Eaux calmes, mares, étangs, fossés|C1/C3|Potamion|Feuilles flottantes ovales coriaces, long pétiole, épis émergés|aquatique commune
Potamot crépu|Potamogeton crispus|Potamogetonaceae|Alismatales|Monocotylédones|Eaux calmes à lentes, fossés, rivières|C1/C2|Potamion|Feuilles submergées ondulées crispées, sans feuilles flottantes|aquatique commune
Lentille d'eau|Lemna minor|Araceae|Alismatales|Monocotylédones|Mares, fossés, eaux stagnantes eutrophes|C1|Lemnion minoris|Petites frondes flottantes rondes, racine unique|aquatique commune
Nénuphar jaune|Nuphar lutea|Nymphaeaceae|Nymphaeales|Angiospermes basales|Étangs, boires, rivières lentes|C1/C2|Nupharo-Potamion|Grandes feuilles flottantes, fleurs jaunes globuleuses|aquatique commune
Nénuphar blanc|Nymphaea alba|Nymphaeaceae|Nymphaeales|Angiospermes basales|Étangs, mares, eaux calmes|C1|Nymphaeion|Grandes feuilles flottantes, grandes fleurs blanches|patrimoniale à vérifier
Jussie à grandes fleurs|Ludwigia grandiflora|Onagraceae|Myrtales|Eudicotylédones|Berges, boires, fossés, eaux lentes|C3/J|Herbiers invasifs|Plante aquatique rampante, grandes fleurs jaunes, feuilles alternes|invasive avérée à vérifier
Jussie rampante|Ludwigia peploides|Onagraceae|Myrtales|Eudicotylédones|Eaux lentes, berges vaseuses, fossés|C3/J|Herbiers invasifs|Plante amphibie rampante, fleurs jaunes, stolons flottants|invasive avérée à vérifier
Élodée du Canada|Elodea canadensis|Hydrocharitaceae|Alismatales|Monocotylédones|Eaux calmes, fossés, étangs|C1/C2|Potamion perturbé|Plante submergée, feuilles verticillées par 3, herbiers denses|invasive/naturalisée à vérifier
Élodée de Nuttall|Elodea nuttallii|Hydrocharitaceae|Alismatales|Monocotylédones|Eaux calmes, canaux, étangs|C1/C2|Potamion perturbé|Feuilles étroites souvent recourbées, herbiers submergés denses|invasive avérée à vérifier
Myriophylle du Brésil|Myriophyllum aquaticum|Haloragaceae|Saxifragales|Eudicotylédones|Mares, fossés, eaux lentes|C1/C3|Herbiers invasifs|Tiges flottantes, feuilles finement divisées en verticilles, parties émergées|invasive avérée à vérifier
Azolla fausse-fougère|Azolla filiculoides|Salviniaceae|Salviniales|Ptéridophytes|Mares, fossés, eaux stagnantes eutrophes|C1|Lemnion perturbé|Petite fougère flottante rougeâtre formant des tapis|invasive à surveiller
`.trim().split('\n');
let next=Math.max(...DATA.plants.map(p=>p.id||0))+1;
rows.forEach(r=>{let a=r.split('|');if(DATA.plants.some(p=>p.latin===a[1]))return;DATA.plants.push({id:next++,fr:a[0],latin:a[1],family:a[2],classif:{ordre:a[3],classe:a[4],famille:a[2]},biotope:a[5],habitat:a[5],eunis:a[6],syntaxon:a[7],criteria:a[8],status:a[9]||'commune',confusions:'À vérifier avec flore locale si doute.',ecology:a[5]})});
DATA.plants.sort((a,b)=>a.fr.localeCompare(b.fr,'fr')).forEach((p,i)=>p.id=i+1);
})();
