// Botadex : fiches plantes pro, classification propre et criteres d'identification renforces.
(function(){
const F={
Asteraceae:["Eudicotyledones","Asterales","Capitules composes de fleurs ligulees ou tubulees, involucre de bractees, fruits en akenes ou cypseles."],
Poaceae:["Monocotyledones","Poales","Tige a noeuds, feuilles a gaine, ligule, epillets avec glumes et lemmes."],
Cyperaceae:["Monocotyledones","Poales","Tige souvent triangulaire, feuilles en trois rangs, epis, utricules chez Carex."],
Juncaceae:["Monocotyledones","Poales","Tiges ou feuilles joncoides, fleurs discretes a six tepales, capsules, milieux souvent humides."],
Ericaceae:["Eudicotyledones","Ericales","Sous-arbrisseaux acidiphiles, feuilles petites et coriaces, fleurs en grelots ou corolles."],
Fabaceae:["Eudicotyledones","Fabales","Feuilles souvent composees, stipules frequentes, fleurs papilionacees, fruits en gousses."],
Rosaceae:["Eudicotyledones","Rosales","Fleurs souvent a cinq petales et nombreuses etamines, stipules frequentes, fruits varies."],
Caryophyllaceae:["Eudicotyledones","Caryophyllales","Feuilles opposees, noeuds marques, fleurs souvent a cinq petales, capsule frequente."],
Orchidaceae:["Monocotyledones","Asparagales","Fleur zygomorphe avec labelle, ovaire infere, feuilles entieres souvent basales."],
Iridaceae:["Monocotyledones","Asparagales","Feuilles en glaive, fleurs a six tepales, ovaire infere, souvent rhizome."],
Betulaceae:["Eudicotyledones","Fagales","Ligneux a feuilles simples, fleurs en chatons, fruits petits, criteres sur feuilles et infrutescences."],
Urticaceae:["Eudicotyledones","Rosales","Feuilles souvent opposees, poils urticants possibles, petites fleurs verdatres."],
Caprifoliaceae:["Eudicotyledones","Dipsacales","Feuilles souvent opposees, inflorescences compactes, fruits variables."],
Sphagnaceae:["Sphagnopsida","Sphagnales","Mousse spongieuse a capitulum terminal et rameaux fascicules, milieux tourbeux."],
Dennstaedtiaceae:["Polypodiopsida","Polypodiales","Fougeres a frondes divisees, sores et rhizome a observer."],
Droseraceae:["Eudicotyledones","Caryophyllales","Petites plantes carnivores a poils glanduleux, milieux tourbeux acides."]
};
const V={
"Achillea millefolium":["Achillee millefeuille","Asteraceae","Achillea","Feuilles tres decoupees en segments fins donnant un aspect plumeux ; capitules blancs ou roses en corymbe plat.","Feuilles alternes, plante aromatique, tige dressee, akene sec.","Matricaria, Anthemis, autres Asteraceae blanches.","Floraison et feuilles bien developpees."],
"Centaurea jacea":["Centauree jacee","Asteraceae","Centaurea","Capitules pourpres, bractees de l'involucre scarieuses ou frangees, plante de prairie.","Feuilles alternes, port robuste, capitule solitaire ou peu nombreux.","Centaurea nigra et autres centaurees.","Floraison, avec involucre visible."],
"Molinia caerulea":["Molinie bleue","Poaceae","Molinia","Graminee en touffes denses, panicule fine souvent violacee, ligule reduite en rang de poils.","Feuilles longues et etroites, sols humides acides, prairie oligotrophe.","Deschampsia, autres Poaceae de prairie humide.","Panicule developpee, base de feuille observable."],
"Succisa pratensis":["Succise des pres","Caprifoliaceae","Succisa","Capitules bleu violet hemispheriques, feuilles entieres, prairie humide maigre.","Souvent avec Molinia, Carex panicea, Potentilla erecta ; port simple.","Knautia, Scabiosa.","Floraison, capitule et feuilles visibles."],
"Carex panicea":["Carex panicea","Cyperaceae","Carex","Laiche glauque de prairie humide, epis males et femelles separes, utricules a observer.","Feuilles glauques, port peu robuste, sols pauvres et humides.","Carex flacca, Carex nigra, autres Carex.","Utricules murs indispensables."],
"Juncus acutiflorus":["Jonc acutiflore","Juncaceae","Juncus","Jonc de prairie humide acide, inflorescence lache, tepales aigus.","Verifier feuilles ou tiges cloisonnees, capsule, habitat humide acide.","Juncus articulatus, Juncus effusus.","Fleurs ou capsules visibles."],
"Iris pseudacorus":["Iris jaune","Iridaceae","Iris","Grand helophyte a feuilles en glaive, fleurs jaunes, rhizome, capsule allongee.","Bords de mares, fosses, berges ; nervure mediane marquee.","Iris horticoles echappes.","Floraison ou fruits, feuilles entieres visibles."],
"Phragmites australis":["Phragmite commun","Poaceae","Phragmites","Tres grand roseau, tiges robustes, feuilles larges, panicule terminale plumeuse.","Peuplements denses de roseliere, fosses ou berges eutrophes.","Phalaris arundinacea.","Panicule developpee et vue du peuplement."],
"Calluna vulgaris":["Callune","Ericaceae","Calluna","Sous arbrisseau bas, petites feuilles opposees imbriquees, fleurs roses.","Tiges ligneuses, landes acides, sols pauvres.","Erica spp.","Fleurs ou rameaux bien visibles."],
"Erica tetralix":["Bruyere a quatre angles","Ericaceae","Erica","Feuilles verticillees par quatre, fleurs roses en grelots regroupees en tete terminale.","Lande humide acide, souvent avec Molinia et sphaignes.","Erica cinerea, Calluna vulgaris.","Floraison et rameaux visibles."],
"Urtica dioica":["Grande ortie","Urticaceae","Urtica","Feuilles opposees dentees, poils urticants, inflorescences verdatres pendantes.","Vivace nitrophile de sols riches, ourlets, friches, berges.","Lamium avant floraison.","Feuilles et poils observables."],
"Robinia pseudoacacia":["Robinier faux-acacia","Fabaceae","Robinia","Arbre a feuilles composees imparipennees, stipules epineuses, fleurs blanches en grappes, gousses.","Ecorce crevassee, colonisation par rejets, friches et talus.","Sophora, jeunes Fraxinus.","Feuilles et rameaux epineux ; fleurs ou gousses si possible."],
"Anacamptis morio":["Orchis bouffon","Orchidaceae","Anacamptis","Orchidee prairiale, casque a nervures vertes, labelle trilobe ponctue, feuilles basales non tachetees.","Inflorescence assez lache, prairie maigre ou pelouse.","Anacamptis laxiflora et autres orchidees.","Floraison ; photo de face et de profil."],
"Alnus glutinosa":["Aulne glutineux","Betulaceae","Alnus","Arbre de zones humides, feuilles arrondies souvent tronquees au sommet, petits cones ligneux persistants.","Jeunes feuilles parfois glutineuses, chatons, bas fonds humides.","Noisetier, bouleaux jeunes.","Feuilles + cones ou chatons."],
"Filipendula ulmaria":["Reine des pres","Rosaceae","Filipendula","Grande vivace hygrophile, feuilles composees, grande foliole terminale, panicules creme parfumees.","Prairies humides hautes, megaphorbiaies, fosses.","Aruncus, Spiraea horticoles.","Floraison et feuille composee visible."],
"Silene flos-cuculi":["Lychnis fleur de coucou","Caryophyllaceae","Silene","Fleurs roses a petales tres decoupes en lanieres, feuilles opposees, tige fine.","Prairie humide peu intensive, floraison printaniere.","Silene dioica, autres Caryophyllaceae roses.","Floraison."],
"Phalaris arundinacea":["Baldingere faux roseau","Poaceae","Phalaris","Grande graminee de berges, feuilles larges, panicule d'abord compacte puis etalee.","Fosses, berges, prairies inondables eutrophes.","Phragmites australis.","Panicule visible."],
"Sphagnum spp.":["Sphaignes","Sphagnaceae","Sphagnum","Mousse spongieuse de tourbiere, capitulum terminal, rameaux en faisceaux, forte retention d'eau.","Milieux tourbeux acides, coussins ou tapis humides.","Autres mousses ; espece exacte delicate.","Loupe, habitat, eventuellement microscope."],
"Pteridium aquilinum":["Fougere aigle","Dennstaedtiaceae","Pteridium","Grande fougere en nappes, fronde triangulaire tres divisee, long rhizome tracant.","Landes, bois acides, coupes forestieres.","Dryopteris, autres grandes fougeres.","Fronde complete et habitat."],
"Drosera rotundifolia":["Drosera a feuilles rondes","Droseraceae","Drosera","Petite plante carnivore, feuilles rondes en rosette avec poils glanduleux rouges collants.","Tourbiere acide, sphaignes, substrat oligotrophe.","Drosera intermedia.","Feuilles visibles, habitat tourbeux."]
};
const G={prairie:"Verifier port, feuilles, inflorescence, floraison et cortege prairial.",humide:"Verifier hydromorphie, joncs/carex, sol frais ou engorge.",carex:"Observer tige, gaine, epis, utricules murs, bec et glumes.",juncus:"Observer tige, feuilles cloisonnees, tepales, capsule et habitat humide.",helophyte:"Verifier enracinement dans vase/eau, tiges emergees, ceinture de berge.",lande:"Observer sous arbrisseau, feuilles petites, acidiphilie, sol pauvre.",ruderal:"Chercher perturbation, azote, sol remanie, especes nitrophiles.",invasive:"Noter densite, surface, reproduction et risque de dispersion.",orchidee:"Observer labelle, eperon, bractees, feuilles basales, fleur de face/profil.",tourbiere:"Verifier sphaignes, tourbe, eau acide, oligotrophie.",bryophyte:"Observer substrat, humidite, architecture ; validation specifique delicate.",fougere:"Observer fronde, sores, petiole, rhizome et habitat."};
function clean(x){return String(x||"").replace(" agg.","").replace(/ · fiche locale .*/,"").trim()}
function val(x){return x===undefined||x===null||x===""?"—":x}
function hit(p){return V[clean(p.latin)]||Object.values(V).find(a=>String(p.fr||"").startsWith(a[0]))}
function enrich(p){const h=hit(p);if(h){p.fr=String(p.fr||"").includes("fiche locale")?h[0]:p.fr;p.latin=clean(p.latin);p.family=h[1];p.criteria=h[3];p.confusions=p.confusions||h[5];p.proStatus=p.detailed?"fiche verifiee a consolider":"fiche modele verifiee a consolider"}const fam=F[p.family]||["—","—","Observer port, feuilles, tige, fleurs, fruits, pilosite, habitat et cortege."];const genre=h?h[2]:(clean(p.latin).split(" ")[0]||"—");const gc=G[p.group]||G[String(p.group||"").split(" ")[0]]||"Croiser morphologie, habitat, phenologie et cortege.";p.classif={regne:"Plantae",embranchement:p.family==="Sphagnaceae"?"Bryophytes":p.family==="Dennstaedtiaceae"?"Pteridophytes":"Tracheophytes",clade:p.family==="Sphagnaceae"?"Bryophytes":p.family==="Dennstaedtiaceae"?"Pteridophytes":"Angiospermes",classe:fam[0],ordre:fam[1],famille:p.family||"—",genre:genre,taxon:p.latin||p.fr||"—"};p.identification={essentiel:p.criteria||fam[2],complementaire:h?h[4]:fam[2],famille:fam[2],groupe:gc,feuille:"Disposition, limbe, marge, nervation, petiole/gaine/stipules, pilosite.",tige:"Section, noeuds, pilosite, rameaux, rhizome ou stolon si visible.",fleur:"Inflorescence, symetrie, calice, corolle, etamines, ovaire, couleur.",fruit:"Type de fruit mur, forme, mode d'ouverture, graines si visibles.",confusion:h?h[5]:(p.confusions||"A verifier avec flore et organes murs."),stade:h?h[6]:"Observer si possible fleurs et fruits murs.",photos:"Port entier, feuille dessus/dessous, tige, fleur, fruit, habitat.",fiabilite:h?"bonne base pour fiche reelle ; source officielle a verifier":"criteres par famille/groupe ; validation specifique a faire"};return p}
if(window.DATA&&Array.isArray(DATA.plants))DATA.plants.forEach(enrich);
window.openPlant=function(id){const p=enrich(DATA.plants.find(x=>x.id===id));const n=state.notes[id]||"",photos=state.photos[id]||[],c=p.classif,ic=p.identification;modalContent.innerHTML='<h2>'+val(p.fr)+'</h2><div class="latin">'+val(p.latin)+' · '+val(p.family)+'</div><div class="badges"><span class="badge">'+val(p.group)+'</span><span class="badge">'+val(p.proStatus)+'</span><span class="badge">'+val(p.eunis)+'</span><span class="badge">'+val(p.syntaxon)+'</span></div><section class="module"><h3>Classement taxonomique</h3><table><tr><th>Rang</th><th>Valeur</th></tr><tr><td>Regne</td><td>'+val(c.regne)+'</td></tr><tr><td>Embranchement</td><td>'+val(c.embranchement)+'</td></tr><tr><td>Clade</td><td>'+val(c.clade)+'</td></tr><tr><td>Classe</td><td>'+val(c.classe)+'</td></tr><tr><td>Ordre</td><td>'+val(c.ordre)+'</td></tr><tr><td>Famille</td><td>'+val(c.famille)+'</td></tr><tr><td>Genre</td><td>'+val(c.genre)+'</td></tr><tr><td>Taxon</td><td><i>'+val(c.taxon)+'</i></td></tr></table></section><h3>Galerie personnelle — 6 photos</h3><p>La photo 1 devient automatiquement la couverture.</p><div class="photo-grid">'+[0,1,2,3,4,5].map(i=>'<label class="photo-slot">'+(photos[i]?'<img src="'+photos[i]+'">':'Photo '+(i+1)+'<br>'+(i===0?'couverture':''))+'<input hidden type="file" accept="image/*" onchange="addPhoto('+id+','+i+',this)"></label>').join('')+'</div><section class="module"><h3>Critères d identification</h3><table><tr><th>Bloc</th><th>A verifier</th></tr><tr><td>Essentiel</td><td>'+val(ic.essentiel)+'</td></tr><tr><td>Complementaire</td><td>'+val(ic.complementaire)+'</td></tr><tr><td>Famille</td><td>'+val(ic.famille)+'</td></tr><tr><td>Groupe/habitat</td><td>'+val(ic.groupe)+'</td></tr><tr><td>Feuille</td><td>'+val(ic.feuille)+'</td></tr><tr><td>Tige</td><td>'+val(ic.tige)+'</td></tr><tr><td>Fleur</td><td>'+val(ic.fleur)+'</td></tr><tr><td>Fruit</td><td>'+val(ic.fruit)+'</td></tr><tr><td>Confusions</td><td>'+val(ic.confusion)+'</td></tr><tr><td>Stade ideal</td><td>'+val(ic.stade)+'</td></tr><tr><td>Photos a prendre</td><td>'+val(ic.photos)+'</td></tr><tr><td>Fiabilite</td><td>'+val(ic.fiabilite)+'</td></tr></table></section><div class="two-col"><section class="module"><h3>Description</h3><p>'+val(p.description)+'</p><p><b>Habitat :</b> '+val(p.habitat)+'</p></section><section class="module"><h3>Ecologie</h3><p>'+val(p.ecology)+'</p></section><section class="module"><h3>Confusions</h3><p>'+val(p.confusions)+'</p></section><section class="module"><h3>Niveau expert</h3><p>'+val(p.expert)+'</p></section></div><h3>Notes personnelles</h3><textarea id="note">'+n+'</textarea><div class="actions"><button class="primary" onclick="state.notes['+id+']=$(\'#note\').value;save();closeModal();render()">Sauvegarder</button><button class="secondary" onclick="removePhotos('+id+')">Retirer photos</button></div>';modal.showModal()};
if(typeof render==="function")render();
})();